use crate::protocol::bedrock::actor_event::ActorEvent;
use crate::protocol::bedrock::actor_pick_request::ActorPickRequest;
use crate::protocol::bedrock::add_actor::AddActor;
use crate::protocol::bedrock::add_behavior_tree::AddBehaviorTree;
use crate::protocol::bedrock::add_item_actor::AddItemActor;
use crate::protocol::bedrock::add_painting::AddPainting;
use crate::protocol::bedrock::add_player::AddPlayer;
use crate::protocol::bedrock::add_volume_entity::AddVolumeEntity;
use crate::protocol::bedrock::agent_action_event::AgentActionEvent;
use crate::protocol::bedrock::agent_animation::AgentAnimation;
use crate::protocol::bedrock::animate::Animate;
use crate::protocol::bedrock::animate_entity::AnimateEntity;
use crate::protocol::bedrock::anvil_damage::AnvilDamage;
use crate::protocol::bedrock::automation_client_connect::AutomationClientConnect;
use crate::protocol::bedrock::available_actor_identifiers::AvailableActorIdentifiers;
use crate::protocol::bedrock::available_commands::AvailableCommands;
use crate::protocol::bedrock::award_achievement::AwardAchievement;
use crate::protocol::bedrock::biome_definition_list::BiomeDefinitionList;
use crate::protocol::bedrock::block_actor_data::BlockActorData;
use crate::protocol::bedrock::block_event::BlockEvent;
use crate::protocol::bedrock::block_pick_request::BlockPickRequest;
use crate::protocol::bedrock::book_edit::BookEdit;
use crate::protocol::bedrock::boss_event::BossEvent;
use crate::protocol::bedrock::camera::Camera;
use crate::protocol::bedrock::camera_aim_assist::CameraAimAssist;
use crate::protocol::bedrock::camera_aim_assist_presets::CameraAimAssistPresets;
use crate::protocol::bedrock::camera_instruction::CameraInstruction;
use crate::protocol::bedrock::camera_presets::CameraPresets;
use crate::protocol::bedrock::camera_shake::CameraShake;
use crate::protocol::bedrock::change_dimension::ChangeDimension;
use crate::protocol::bedrock::change_mob_property::ChangeMobProperty;
use crate::protocol::bedrock::chunk_radius_updated::ChunkRadiusUpdated;
use crate::protocol::bedrock::client_bound_close_form::ClientBoundCloseForm;
use crate::protocol::bedrock::client_bound_control_scheme_set::ClientBoundControlSchemeSet;
use crate::protocol::bedrock::client_bound_data_store::ClientBoundDataStore;
use crate::protocol::bedrock::client_bound_debug_renderer::ClientBoundDebugRenderer;
use crate::protocol::bedrock::client_bound_map_item_data::ClientBoundMapItemData;
use crate::protocol::bedrock::client_cache_blob_status::ClientCacheBlobStatus;
use crate::protocol::bedrock::client_cache_miss_response::ClientCacheMissResponse;
use crate::protocol::bedrock::client_cache_status::ClientCacheStatus;
use crate::protocol::bedrock::client_camera_aim_assist::ClientCameraAimAssist;
use crate::protocol::bedrock::client_movement_prediction_sync::ClientMovementPredictionSync;
use crate::protocol::bedrock::client_to_server_handshake::ClientToServerHandshake;
use crate::protocol::bedrock::code_builder::CodeBuilder;
use crate::protocol::bedrock::code_builder_source::CodeBuilderSource;
use crate::protocol::bedrock::command_block_update::CommandBlockUpdate;
use crate::protocol::bedrock::command_output::CommandOutput;
use crate::protocol::bedrock::command_request::CommandRequest;
use crate::protocol::bedrock::completed_using_item::CompletedUsingItem;
use crate::protocol::bedrock::container_close::ContainerClose;
use crate::protocol::bedrock::container_open::ContainerOpen;
use crate::protocol::bedrock::container_registry_cleanup::ContainerRegistryCleanup;
use crate::protocol::bedrock::container_set_data::ContainerSetData;
use crate::protocol::bedrock::correct_player_move_prediction::CorrectPlayerMovePrediction;
use crate::protocol::bedrock::crafting_data::CraftingData;
use crate::protocol::bedrock::create_photo::CreatePhoto;
use crate::protocol::bedrock::creative_content::CreativeContent;
use crate::protocol::bedrock::current_structure_feature::CurrentStructureFeature;
use crate::protocol::bedrock::death_info::DeathInfo;
use crate::protocol::bedrock::debug_drawer::DebugDrawer;
use crate::protocol::bedrock::debug_info::DebugInfo;
use crate::protocol::bedrock::dimension_data::DimensionData;
use crate::protocol::bedrock::disconnect::Disconnect;
use crate::protocol::bedrock::editor_network::EditorNetwork;
use crate::protocol::bedrock::edu_uri_resource::EduUriResource;
use crate::protocol::bedrock::education_settings::EducationSettings;
use crate::protocol::bedrock::emote::Emote;
use crate::protocol::bedrock::emote_list::EmoteList;
use crate::protocol::bedrock::feature_registry::FeatureRegistry;
use crate::protocol::bedrock::game_rules_changed::GameRulesChanged;
use crate::protocol::bedrock::game_test_request::GameTestRequest;
use crate::protocol::bedrock::game_test_results::GameTestResults;
use crate::protocol::bedrock::graphics_override_parameter::GraphicsOverrideParameter;
use crate::protocol::bedrock::gui_data_pick_item::GUIDataPickItem;
use crate::protocol::bedrock::hurt_armor::HurtArmor;
use crate::protocol::bedrock::interact::Interact;
use crate::protocol::bedrock::inventory_content::InventoryContent;
use crate::protocol::bedrock::inventory_slot::InventorySlot;
use crate::protocol::bedrock::inventory_transaction::InventoryTransaction;
use crate::protocol::bedrock::item_registry::ItemRegistry;
use crate::protocol::bedrock::item_stack_request::ItemStackRequest;
use crate::protocol::bedrock::item_stack_response::ItemStackResponse;
use crate::protocol::bedrock::jigsaw_structure_data::JigsawStructureData;
use crate::protocol::bedrock::lab_table::LabTable;
use crate::protocol::bedrock::lectern_update::LecternUpdate;
use crate::protocol::bedrock::legacy_telemetry_event::LegacyTelemetryEvent;
use crate::protocol::bedrock::lesson_progress::LessonProgress;
use crate::protocol::bedrock::level_chunk::LevelChunk;
use crate::protocol::bedrock::level_event::LevelEvent;
use crate::protocol::bedrock::level_event_generic::LevelEventGeneric;
use crate::protocol::bedrock::level_sound_event::LevelSoundEvent;
use crate::protocol::bedrock::login::Login;
use crate::protocol::bedrock::map_create_locked_copy::MapCreateLockedCopy;
use crate::protocol::bedrock::map_info_request::MapInfoRequest;
use crate::protocol::bedrock::mob_armor_equipment::MobArmorEquipment;
use crate::protocol::bedrock::mob_effect::MobEffect;
use crate::protocol::bedrock::mob_equipment::MobEquipment;
use crate::protocol::bedrock::modal_form_request::ModalFormRequest;
use crate::protocol::bedrock::modal_form_response::ModalFormResponse;
use crate::protocol::bedrock::motion_prediction_hints::MotionPredictionHints;
use crate::protocol::bedrock::move_actor_absolute::MoveActorAbsolute;
use crate::protocol::bedrock::move_actor_delta::MoveActorDelta;
use crate::protocol::bedrock::move_player::MovePlayer;
use crate::protocol::bedrock::movement_effect::MovementEffect;
use crate::protocol::bedrock::multiplayer_settings::MultiplayerSettings;
use crate::protocol::bedrock::network_chunk_publisher_update::NetworkChunkPublisherUpdate;
use crate::protocol::bedrock::network_settings::NetworkSettings;
use crate::protocol::bedrock::network_stack_latency::NetworkStackLatency;
use crate::protocol::bedrock::npc_dialogue::NPCDialogue;
use crate::protocol::bedrock::npc_request::NPCRequest;
use crate::protocol::bedrock::on_screen_texture_animation::OnScreenTextureAnimation;
use crate::protocol::bedrock::open_sign::OpenSign;
use crate::protocol::bedrock::packet::Packet;
use crate::protocol::bedrock::packet_violation_warning::PacketViolationWarning;
use crate::protocol::bedrock::photo_transfer::PhotoTransfer;
use crate::protocol::bedrock::play_sound::PlaySound;
use crate::protocol::bedrock::play_status::PlayStatus;
use crate::protocol::bedrock::player_action::PlayerAction;
use crate::protocol::bedrock::player_armor_damage::PlayerArmorDamage;
use crate::protocol::bedrock::player_auth_input::PlayerAuthInput;
use crate::protocol::bedrock::player_enchant_options::PlayerEnchantOptions;
use crate::protocol::bedrock::player_fog::PlayerFog;
use crate::protocol::bedrock::player_hotbar::PlayerHotbar;
use crate::protocol::bedrock::player_list::PlayerList;
use crate::protocol::bedrock::player_location::PlayerLocation;
use crate::protocol::bedrock::player_skin::PlayerSkin;
use crate::protocol::bedrock::player_start_item_cooldown::PlayerStartItemCooldown;
use crate::protocol::bedrock::player_toggle_crafter_slot_request::PlayerToggleCrafterSlotRequest;
use crate::protocol::bedrock::player_update_entity_overrides::PlayerUpdateEntityOverrides;
use crate::protocol::bedrock::player_video_capture::PlayerVideoCapture;
use crate::protocol::bedrock::position_tracking_db_client_request::PositionTrackingDBClientRequest;
use crate::protocol::bedrock::position_tracking_db_server_broadcast::PositionTrackingDBServerBroadcast;
use crate::protocol::bedrock::purchase_receipt::PurchaseReceipt;
use crate::protocol::bedrock::refresh_entitlements::RefreshEntitlements;
use crate::protocol::bedrock::remove_actor::RemoveActor;
use crate::protocol::bedrock::remove_objective::RemoveObjective;
use crate::protocol::bedrock::remove_volume_entity::RemoveVolumeEntity;
use crate::protocol::bedrock::req_network_settings::RequestNetworkSettings;
use crate::protocol::bedrock::request_ability::RequestAbility;
use crate::protocol::bedrock::request_chunk_radius::RequestChunkRadius;
use crate::protocol::bedrock::request_permissions::RequestPermissions;
use crate::protocol::bedrock::resource_pack_chunk_data::ResourcePackChunkData;
use crate::protocol::bedrock::resource_pack_chunk_request::ResourcePackChunkRequest;
use crate::protocol::bedrock::resource_pack_client_response::ResourcePackClientResponse;
use crate::protocol::bedrock::resource_pack_data_info::ResourcePackDataInfo;
use crate::protocol::bedrock::resource_pack_stack::ResourcePackStack;
use crate::protocol::bedrock::resource_packs_info::ResourcePacksInfo;
use crate::protocol::bedrock::respawn::Respawn;
use crate::protocol::bedrock::script_message::ScriptMessage;
use crate::protocol::bedrock::server_bound_data_store::ServerBoundDataStore;
use crate::protocol::bedrock::server_bound_diagnostics::ServerBoundDiagnostics;
use crate::protocol::bedrock::server_bound_loading_screen::ServerBoundLoadingScreen;
use crate::protocol::bedrock::server_bound_pack_setting_change::ServerBoundPackSettingChange;
use crate::protocol::bedrock::server_player_post_move_position::ServerPlayerPostMovePosition;
use crate::protocol::bedrock::server_settings_request::ServerSettingsRequest;
use crate::protocol::bedrock::server_settings_response::ServerSettingsResponse;
use crate::protocol::bedrock::server_stats::ServerStats;
use crate::protocol::bedrock::server_to_client_handshake::ServerToClientHandshake;
use crate::protocol::bedrock::set_actor_data::SetActorData;
use crate::protocol::bedrock::set_actor_link::SetActorLink;
use crate::protocol::bedrock::set_actor_motion::SetActorMotion;
use crate::protocol::bedrock::set_commands_enabled::SetCommandsEnabled;
use crate::protocol::bedrock::set_default_game_type::SetDefaultGameType;
use crate::protocol::bedrock::set_difficulty::SetDifficulty;
use crate::protocol::bedrock::set_display_objective::SetDisplayObjective;
use crate::protocol::bedrock::set_health::SetHealth;
use crate::protocol::bedrock::set_hud::SetHud;
use crate::protocol::bedrock::set_last_hurt_by::SetLastHurtBy;
use crate::protocol::bedrock::set_local_player_as_initialized::SetLocalPlayerAsInitializedPacket;
use crate::protocol::bedrock::set_player_game_type::SetPlayerGameType;
use crate::protocol::bedrock::set_player_inventory_options::SetPlayerInventoryOptions;
use crate::protocol::bedrock::set_score::SetScore;
use crate::protocol::bedrock::set_scoreboard_identity::SetScoreboardIdentity;
use crate::protocol::bedrock::set_spawn_position::SetSpawnPosition;
use crate::protocol::bedrock::set_time::SetTime;
use crate::protocol::bedrock::set_title::SetTitle;
use crate::protocol::bedrock::settings_command::SettingsCommand;
use crate::protocol::bedrock::show_credits::ShowCredits;
use crate::protocol::bedrock::show_profile::ShowProfile;
use crate::protocol::bedrock::show_store_offer::ShowStoreOffer;
use crate::protocol::bedrock::simple_event::SimpleEvent;
use crate::protocol::bedrock::simulation_type::SimulationType;
use crate::protocol::bedrock::spawn_experience_orb::SpawnExperienceOrb;
use crate::protocol::bedrock::spawn_particle_effect::SpawnParticleEffect;
use crate::protocol::bedrock::start_game::StartGame;
use crate::protocol::bedrock::stop_sound::StopSound;
use crate::protocol::bedrock::structure_block_update::StructureBlockUpdate;
use crate::protocol::bedrock::structure_template_data_request::StructureTemplateDataRequest;
use crate::protocol::bedrock::structure_template_data_response::StructureTemplateDataResponse;
use crate::protocol::bedrock::sub_chunk::SubChunk;
use crate::protocol::bedrock::sub_chunk_request::SubChunkRequest;
use crate::protocol::bedrock::sub_client_login::SubClientLogin;
use crate::protocol::bedrock::sync_actor_property::SyncActorProperty;
use crate::protocol::bedrock::take_item_actor::TakeItemActor;
use crate::protocol::bedrock::text::Text;
use crate::protocol::bedrock::ticking_areas_load_status::TickingAreasLoadStatus;
use crate::protocol::bedrock::toast_request::ToastRequest;
use crate::protocol::bedrock::transfer::Transfer;
use crate::protocol::bedrock::trim_data::TrimData;
use crate::protocol::bedrock::unknown::Unknown;
use crate::protocol::bedrock::unlocked_recipes::UnlockedRecipes;
use crate::protocol::bedrock::update_abilities::UpdateAbilities;
use crate::protocol::bedrock::update_adventure_settings::UpdateAdventureSettings;
use crate::protocol::bedrock::update_attributes::UpdateAttributes;
use crate::protocol::bedrock::update_block::UpdateBlock;
use crate::protocol::bedrock::update_block_synced::UpdateBlockSynced;
use crate::protocol::bedrock::update_client_input_locks::UpdateClientInputLocks;
use crate::protocol::bedrock::update_client_options::UpdateClientOptions;
use crate::protocol::bedrock::update_equip::UpdateEquip;
use crate::protocol::bedrock::update_player_game_type::UpdatePlayerGameType;
use crate::protocol::bedrock::update_soft_enum::UpdateSoftEnum;
use crate::protocol::bedrock::update_sub_chunk_blocks::UpdateSubChunkBlocks;
use crate::protocol::bedrock::update_trade::UpdateTrade;
use crate::protocol::bedrock::camera_aim_assist_actor_priority::CameraAimAssistActorPriority;
use crate::protocol::bedrock::camera_spline::CameraSpline;
use crate::protocol::bedrock::client_bound_data_driven_ui_close_all_screens::ClientBoundDataDrivenUICloseAllScreens;
use crate::protocol::bedrock::client_bound_data_driven_ui_reload::ClientBoundDataDrivenUIReload;
use crate::protocol::bedrock::client_bound_data_driven_ui_show_screen::ClientBoundDataDrivenUIShowScreen;
use crate::protocol::bedrock::client_bound_texture_shift::ClientBoundTextureShift;
use crate::protocol::bedrock::voxel_shapes::VoxelShapes;
use binary_utils::binary::Stream;

#[repr(u16)]
pub enum BedrockPacketType {
    IDLogin,
    IDPlayStatus,
    IDServerToClientHandshake,
    IDClientToServerHandshake,
    IDDisconnect,
    IDResourcePacksInfo,
    IDResourcePackStack,
    IDResourcePackClientResponse,
    IDText,
    IDSetTime,
    IDStartGame,
    IDAddPlayer,
    IDAddActor,
    IDRemoveActor,
    IDAddItemActor,
    IDServerPlayerPostMovePosition,
    IDTakeItemActor,
    IDMoveActorAbsolute,
    IDMovePlayer,
    IDUpdateBlock,
    IDAddPainting,
    IDLevelSoundEventV1,
    IDLevelEvent,
    IDBlockEvent,
    IDActorEvent,
    IDMobEffect,
    IDUpdateAttributes,
    IDInventoryTransaction,
    IDMobEquipment,
    IDMobArmorEquipment,
    IDInteract,
    IDBlockPickRequest,
    IDActorPickRequest,
    IDPlayerAction,
    IDHurtArmor,
    IDSetActorData,
    IDSetActorMotion,
    IDSetActorLink,
    IDSetHealth,
    IDSetSpawnPosition,
    IDAnimate,
    IDRespawn,
    IDContainerOpen,
    IDContainerClose,
    IDPlayerHotbar,
    IDInventoryContent,
    IDInventorySlot,
    IDContainerSetData,
    IDCraftingData,
    IDGUIDataPickItem,
    IDBlockActorData,
    IDLevelChunk,
    IDSetCommandsEnabled,
    IDSetDifficulty,
    IDChangeDimension,
    IDSetPlayerGameType,
    IDPlayerList,
    IDSimpleEvent,
    IDLegacyTelemetryEvent,
    IDSpawnExperienceOrb,
    IDClientBoundMapItemData,
    IDMapInfoRequest,
    IDRequestChunkRadius,
    IDChunkRadiusUpdated,
    IDGameRulesChanged,
    IDCamera,
    IDBossEvent,
    IDShowCredits,
    IDAvailableCommands,
    IDCommandRequest,
    IDCommandBlockUpdate,
    IDCommandOutput,
    IDUpdateTrade,
    IDUpdateEquip,
    IDResourcePackDataInfo,
    IDResourcePackChunkData,
    IDResourcePackChunkRequest,
    IDTransfer,
    IDPlaySound,
    IDStopSound,
    IDSetTitle,
    IDAddBehaviorTree,
    IDStructureBlockUpdate,
    IDShowStoreOffer,
    IDPurchaseReceipt,
    IDPlayerSkin,
    IDSubClientLogin,
    IDAutomationClientConnect,
    IDSetLastHurtBy,
    IDBookEdit,
    IDNPCRequest,
    IDPhotoTransfer,
    IDModalFormRequest,
    IDModalFormResponse,
    IDServerSettingsRequest,
    IDServerSettingsResponse,
    IDShowProfile,
    IDSetDefaultGameType,
    IDRemoveObjective,
    IDSetDisplayObjective,
    IDSetScore,
    IDLabTable,
    IDUpdateBlockSynced,
    IDMoveActorDelta,
    IDSetScoreboardIdentity,
    IDSetLocalPlayerAsInitialized,
    IDUpdateSoftEnum,
    IDNetworkStackLatency,
    IDSpawnParticleEffect,
    IDAvailableActorIdentifiers,
    IDNetworkChunkPublisherUpdate,
    IDBiomeDefinitionList,
    IDLevelSoundEvent,
    IDLevelEventGeneric,
    IDLecternUpdate,
    IDClientCacheStatus,
    IDOnScreenTextureAnimation,
    IDMapCreateLockedCopy,
    IDStructureTemplateDataRequest,
    IDStructureTemplateDataResponse,
    IDClientCacheBlobStatus,
    IDClientCacheMissResponse,
    IDEducationSettings,
    IDEmote,
    IDMultiplayerSettings,
    IDSettingsCommand,
    IDAnvilDamage,
    IDCompletedUsingItem,
    IDNetworkSettings,
    IDPlayerAuthInput,
    IDCreativeContent,
    IDPlayerEnchantOptions,
    IDItemStackRequest,
    IDItemStackResponse,
    IDPlayerArmorDamage,
    IDCodeBuilder,
    IDUpdatePlayerGameType,
    IDEmoteList,
    IDPositionTrackingDBServerBroadcast,
    IDPositionTrackingDBClientRequest,
    IDDebugInfo,
    IDPacketViolationWarning,
    IDMotionPredictionHints,
    IDAnimateEntity,
    IDCameraShake,
    IDPlayerFog,
    IDCorrectPlayerMovePrediction,
    IDItemRegistry,
    IDClientBoundDebugRenderer,
    IDSyncActorProperty,
    IDAddVolumeEntity,
    IDRemoveVolumeEntity,
    IDSimulationType,
    IDNpcDialogue,
    IDEduUriResource,
    IDCreatePhoto,
    IDUpdateSubChunkBlocks,
    IDSubChunk,
    IDSubChunkRequest,
    IDPlayerStartItemCooldown,
    IDScriptMessage,
    IDCodeBuilderSource,
    IDTickingAreasLoadStatus,
    IDDimensionData,
    IDAgentActionEvent,
    IDChangeMobProperty,
    IDLessonProgress,
    IDRequestAbility,
    IDRequestPermissions,
    IDToastRequest,
    IDUpdateAbilities,
    IDUpdateAdventureSettings,
    IDDeathInfo,
    IDEditorNetwork,
    IDFeatureRegistry,
    IDServerStats,
    IDRequestNetworkSettings,
    IDGameTestRequest,
    IDGameTestResults,
    IDUpdateClientInputLocks,
    IDCameraPresets,
    IDUnlockedRecipes,
    IDCameraInstruction,
    IDTrimData,
    IDOpenSign,
    IDAgentAnimation,
    IDRefreshEntitlements,
    IDPlayerToggleCrafterSlotRequest,
    IDSetPlayerInventoryOptions,
    IDSetHud,
    IDAwardAchievement,
    IDClientBoundCloseForm,
    IDServerBoundLoadingScreen,
    IDJigsawStructureData,
    IDCurrentStructureFeature,
    IDServerBoundDiagnostics,
    IDCameraAimAssist,
    IDContainerRegistryCleanup,
    IDMovementEffect,
    IDCameraAimAssistPresets,
    IDClientCameraAimAssist,
    IDClientMovementPredictionSync,
    IDUpdateClientOptions,
    IDPlayerVideoCapture,
    IDPlayerUpdateEntityOverrides,
    IDPlayerLocation,
    IDClientBoundControlSchemeSet,
    IDDebugDrawer,
    IDServerBoundPackSettingChange,
    IDClientBoundDataStore,
    IDGraphicsOverrideParameter,
    IDServerBoundDataStore,
    IDClientBoundDataDrivenUIShowScreen,
    IDClientBoundDataDrivenUICloseAllScreens,
    IDClientBoundDataDrivenUIReload,
    IDClientBoundTextureShift,
    IDVoxelShapes,
    IDCameraSpline,
    IDCameraAimAssistActorPriority,
    IDUnknown,
}

impl BedrockPacketType {
    pub fn from_byte(byte: u16) -> Self {
        match byte {
            0x01 => BedrockPacketType::IDLogin,
            0x02 => BedrockPacketType::IDPlayStatus,
            0x03 => BedrockPacketType::IDServerToClientHandshake,
            0x04 => BedrockPacketType::IDClientToServerHandshake,
            0x05 => BedrockPacketType::IDDisconnect,
            0x06 => BedrockPacketType::IDResourcePacksInfo,
            0x07 => BedrockPacketType::IDResourcePackStack,
            0x08 => BedrockPacketType::IDResourcePackClientResponse,
            0x09 => BedrockPacketType::IDText,
            0x0a => BedrockPacketType::IDSetTime,
            0x0b => BedrockPacketType::IDStartGame,
            0x0c => BedrockPacketType::IDAddPlayer,
            0x0d => BedrockPacketType::IDAddActor,
            0x0e => BedrockPacketType::IDRemoveActor,
            0x0f => BedrockPacketType::IDAddItemActor,
            0x10 => BedrockPacketType::IDServerPlayerPostMovePosition,
            0x11 => BedrockPacketType::IDTakeItemActor,
            0x12 => BedrockPacketType::IDMoveActorAbsolute,
            0x13 => BedrockPacketType::IDMovePlayer,
            0x15 => BedrockPacketType::IDUpdateBlock,
            0x16 => BedrockPacketType::IDAddPainting,
            0x19 => BedrockPacketType::IDLevelEvent,
            0x1a => BedrockPacketType::IDBlockEvent,
            0x1b => BedrockPacketType::IDActorEvent,
            0x1c => BedrockPacketType::IDMobEffect,
            0x1d => BedrockPacketType::IDUpdateAttributes,
            0x1e => BedrockPacketType::IDInventoryTransaction,
            0x1f => BedrockPacketType::IDMobEquipment,
            0x20 => BedrockPacketType::IDMobArmorEquipment,
            0x21 => BedrockPacketType::IDInteract,
            0x22 => BedrockPacketType::IDBlockPickRequest,
            0x23 => BedrockPacketType::IDActorPickRequest,
            0x24 => BedrockPacketType::IDPlayerAction,
            0x26 => BedrockPacketType::IDHurtArmor,
            0x27 => BedrockPacketType::IDSetActorData,
            0x28 => BedrockPacketType::IDSetActorMotion,
            0x29 => BedrockPacketType::IDSetActorLink,
            0x2a => BedrockPacketType::IDSetHealth,
            0x2b => BedrockPacketType::IDSetSpawnPosition,
            0x2c => BedrockPacketType::IDAnimate,
            0x2d => BedrockPacketType::IDRespawn,
            0x2e => BedrockPacketType::IDContainerOpen,
            0x2f => BedrockPacketType::IDContainerClose,
            0x30 => BedrockPacketType::IDPlayerHotbar,
            0x31 => BedrockPacketType::IDInventoryContent,
            0x32 => BedrockPacketType::IDInventorySlot,
            0x33 => BedrockPacketType::IDContainerSetData,
            0x34 => BedrockPacketType::IDCraftingData,
            0x36 => BedrockPacketType::IDGUIDataPickItem,
            0x38 => BedrockPacketType::IDBlockActorData,
            0x3a => BedrockPacketType::IDLevelChunk,
            0x3b => BedrockPacketType::IDSetCommandsEnabled,
            0x3c => BedrockPacketType::IDSetDifficulty,
            0x3d => BedrockPacketType::IDChangeDimension,
            0x3e => BedrockPacketType::IDSetPlayerGameType,
            0x3f => BedrockPacketType::IDPlayerList,
            0x40 => BedrockPacketType::IDSimpleEvent,
            0x41 => BedrockPacketType::IDLegacyTelemetryEvent,
            0x42 => BedrockPacketType::IDSpawnExperienceOrb,
            0x43 => BedrockPacketType::IDClientBoundMapItemData,
            0x44 => BedrockPacketType::IDMapInfoRequest,
            0x45 => BedrockPacketType::IDRequestChunkRadius,
            0x46 => BedrockPacketType::IDChunkRadiusUpdated,
            0x48 => BedrockPacketType::IDGameRulesChanged,
            0x49 => BedrockPacketType::IDCamera,
            0x4a => BedrockPacketType::IDBossEvent,
            0x4b => BedrockPacketType::IDShowCredits,
            0x4c => BedrockPacketType::IDAvailableCommands,
            0x4d => BedrockPacketType::IDCommandRequest,
            0x4e => BedrockPacketType::IDCommandBlockUpdate,
            0x4f => BedrockPacketType::IDCommandOutput,
            0x50 => BedrockPacketType::IDUpdateTrade,
            0x51 => BedrockPacketType::IDUpdateEquip,
            0x52 => BedrockPacketType::IDResourcePackDataInfo,
            0x53 => BedrockPacketType::IDResourcePackChunkData,
            0x54 => BedrockPacketType::IDResourcePackChunkRequest,
            0x55 => BedrockPacketType::IDTransfer,
            0x56 => BedrockPacketType::IDPlaySound,
            0x57 => BedrockPacketType::IDStopSound,
            0x58 => BedrockPacketType::IDSetTitle,
            0x59 => BedrockPacketType::IDAddBehaviorTree,
            0x5a => BedrockPacketType::IDStructureBlockUpdate,
            0x5b => BedrockPacketType::IDShowStoreOffer,
            0x5c => BedrockPacketType::IDPurchaseReceipt,
            0x5d => BedrockPacketType::IDPlayerSkin,
            0x5e => BedrockPacketType::IDSubClientLogin,
            0x5f => BedrockPacketType::IDAutomationClientConnect,
            0x60 => BedrockPacketType::IDSetLastHurtBy,
            0x61 => BedrockPacketType::IDBookEdit,
            0x62 => BedrockPacketType::IDNPCRequest,
            0x63 => BedrockPacketType::IDPhotoTransfer,
            0x64 => BedrockPacketType::IDModalFormRequest,
            0x65 => BedrockPacketType::IDModalFormResponse,
            0x66 => BedrockPacketType::IDServerSettingsRequest,
            0x67 => BedrockPacketType::IDServerSettingsResponse,
            0x68 => BedrockPacketType::IDShowProfile,
            0x69 => BedrockPacketType::IDSetDefaultGameType,
            0x6a => BedrockPacketType::IDRemoveObjective,
            0x6b => BedrockPacketType::IDSetDisplayObjective,
            0x6c => BedrockPacketType::IDSetScore,
            0x6d => BedrockPacketType::IDLabTable,
            0x6e => BedrockPacketType::IDUpdateBlockSynced,
            0x6f => BedrockPacketType::IDMoveActorDelta,
            0x70 => BedrockPacketType::IDSetScoreboardIdentity,
            0x71 => BedrockPacketType::IDSetLocalPlayerAsInitialized,
            0x72 => BedrockPacketType::IDUpdateSoftEnum,
            0x73 => BedrockPacketType::IDNetworkStackLatency,
            0x76 => BedrockPacketType::IDSpawnParticleEffect,
            0x77 => BedrockPacketType::IDAvailableActorIdentifiers,
            0x79 => BedrockPacketType::IDNetworkChunkPublisherUpdate,
            0x7a => BedrockPacketType::IDBiomeDefinitionList,
            0x7b => BedrockPacketType::IDLevelSoundEvent,
            0x7c => BedrockPacketType::IDLevelEventGeneric,
            0x7d => BedrockPacketType::IDLecternUpdate,
            0x81 => BedrockPacketType::IDClientCacheStatus,
            0x82 => BedrockPacketType::IDOnScreenTextureAnimation,
            0x83 => BedrockPacketType::IDMapCreateLockedCopy,
            0x84 => BedrockPacketType::IDStructureTemplateDataRequest,
            0x85 => BedrockPacketType::IDStructureTemplateDataResponse,
            0x87 => BedrockPacketType::IDClientCacheBlobStatus,
            0x88 => BedrockPacketType::IDClientCacheMissResponse,
            0x89 => BedrockPacketType::IDEducationSettings,
            0x8a => BedrockPacketType::IDEmote,
            0x8b => BedrockPacketType::IDMultiplayerSettings,
            0x8c => BedrockPacketType::IDSettingsCommand,
            0x8d => BedrockPacketType::IDAnvilDamage,
            0x8e => BedrockPacketType::IDCompletedUsingItem,
            0x8f => BedrockPacketType::IDNetworkSettings,
            0x90 => BedrockPacketType::IDPlayerAuthInput,
            0x91 => BedrockPacketType::IDCreativeContent,
            0x92 => BedrockPacketType::IDPlayerEnchantOptions,
            0x93 => BedrockPacketType::IDItemStackRequest,
            0x94 => BedrockPacketType::IDItemStackResponse,
            0x95 => BedrockPacketType::IDPlayerArmorDamage,
            0x96 => BedrockPacketType::IDCodeBuilder,
            0x97 => BedrockPacketType::IDUpdatePlayerGameType,
            0x98 => BedrockPacketType::IDEmoteList,
            0x99 => BedrockPacketType::IDPositionTrackingDBServerBroadcast,
            0x9a => BedrockPacketType::IDPositionTrackingDBClientRequest,
            0x9b => BedrockPacketType::IDDebugInfo,
            0x9c => BedrockPacketType::IDPacketViolationWarning,
            0x9d => BedrockPacketType::IDMotionPredictionHints,
            0x9e => BedrockPacketType::IDAnimateEntity,
            0x9f => BedrockPacketType::IDCameraShake,
            0xa0 => BedrockPacketType::IDPlayerFog,
            0xa1 => BedrockPacketType::IDCorrectPlayerMovePrediction,
            0xa2 => BedrockPacketType::IDItemRegistry,
            0xa4 => BedrockPacketType::IDClientBoundDebugRenderer,
            0xa5 => BedrockPacketType::IDSyncActorProperty,
            0xa6 => BedrockPacketType::IDAddVolumeEntity,
            0xa7 => BedrockPacketType::IDRemoveVolumeEntity,
            0xa8 => BedrockPacketType::IDSimulationType,
            0xa9 => BedrockPacketType::IDNpcDialogue,
            0xaa => BedrockPacketType::IDEduUriResource,
            0xab => BedrockPacketType::IDCreatePhoto,
            0xac => BedrockPacketType::IDUpdateSubChunkBlocks,
            0xae => BedrockPacketType::IDSubChunk,
            0xaf => BedrockPacketType::IDSubChunkRequest,
            0xb0 => BedrockPacketType::IDPlayerStartItemCooldown,
            0xb1 => BedrockPacketType::IDScriptMessage,
            0xb2 => BedrockPacketType::IDCodeBuilderSource,
            0xb3 => BedrockPacketType::IDTickingAreasLoadStatus,
            0xb4 => BedrockPacketType::IDDimensionData,
            0xb5 => BedrockPacketType::IDAgentActionEvent,
            0xb6 => BedrockPacketType::IDChangeMobProperty,
            0xb7 => BedrockPacketType::IDLessonProgress,
            0xb8 => BedrockPacketType::IDRequestAbility,
            0xb9 => BedrockPacketType::IDRequestPermissions,
            0xba => BedrockPacketType::IDToastRequest,
            0xbb => BedrockPacketType::IDUpdateAbilities,
            0xbc => BedrockPacketType::IDUpdateAdventureSettings,
            0xbd => BedrockPacketType::IDDeathInfo,
            0xbe => BedrockPacketType::IDEditorNetwork,
            0xbf => BedrockPacketType::IDFeatureRegistry,
            0xc0 => BedrockPacketType::IDServerStats,
            0xc1 => BedrockPacketType::IDRequestNetworkSettings,
            0xc2 => BedrockPacketType::IDGameTestRequest,
            0xc3 => BedrockPacketType::IDGameTestResults,
            0xc4 => BedrockPacketType::IDUpdateClientInputLocks,
            0xc6 => BedrockPacketType::IDCameraPresets,
            0xc7 => BedrockPacketType::IDUnlockedRecipes,
            0x12c => BedrockPacketType::IDCameraInstruction,
            0x12e => BedrockPacketType::IDTrimData,
            0x12f => BedrockPacketType::IDOpenSign,
            0x130 => BedrockPacketType::IDAgentAnimation,
            0x131 => BedrockPacketType::IDRefreshEntitlements,
            0x132 => BedrockPacketType::IDPlayerToggleCrafterSlotRequest,
            0x133 => BedrockPacketType::IDSetPlayerInventoryOptions,
            0x134 => BedrockPacketType::IDSetHud,
            0x135 => BedrockPacketType::IDAwardAchievement,
            0x136 => BedrockPacketType::IDClientBoundCloseForm,
            0x138 => BedrockPacketType::IDServerBoundLoadingScreen,
            0x139 => BedrockPacketType::IDJigsawStructureData,
            0x13a => BedrockPacketType::IDCurrentStructureFeature,
            0x13b => BedrockPacketType::IDServerBoundDiagnostics,
            0x13c => BedrockPacketType::IDCameraAimAssist,
            0x13d => BedrockPacketType::IDContainerRegistryCleanup,
            0x13e => BedrockPacketType::IDMovementEffect,
            0x140 => BedrockPacketType::IDCameraAimAssistPresets,
            0x141 => BedrockPacketType::IDClientCameraAimAssist,
            0x142 => BedrockPacketType::IDClientMovementPredictionSync,
            0x143 => BedrockPacketType::IDUpdateClientOptions,
            0x144 => BedrockPacketType::IDPlayerVideoCapture,
            0x145 => BedrockPacketType::IDPlayerUpdateEntityOverrides,
            0x146 => BedrockPacketType::IDPlayerLocation,
            0x147 => BedrockPacketType::IDClientBoundControlSchemeSet,
            0x148 => BedrockPacketType::IDDebugDrawer,
            0x149 => BedrockPacketType::IDServerBoundPackSettingChange,
            0x14a => BedrockPacketType::IDClientBoundDataStore,
            0x14b => BedrockPacketType::IDGraphicsOverrideParameter,
            0x14c => BedrockPacketType::IDServerBoundDataStore,
            0x14d => BedrockPacketType::IDClientBoundDataDrivenUIShowScreen,
            0x14e => BedrockPacketType::IDClientBoundDataDrivenUICloseAllScreens,
            0x14f => BedrockPacketType::IDClientBoundDataDrivenUIReload,
            0x150 => BedrockPacketType::IDClientBoundTextureShift,
            0x151 => BedrockPacketType::IDVoxelShapes,
            0x152 => BedrockPacketType::IDCameraSpline,
            0x153 => BedrockPacketType::IDCameraAimAssistActorPriority,
            _ => BedrockPacketType::IDUnknown,
        }
    }
    pub fn get_byte(self) -> u16 {
        match self {
            BedrockPacketType::IDLogin => 0x01,
            BedrockPacketType::IDPlayStatus => 0x02,
            BedrockPacketType::IDServerToClientHandshake => 0x03,
            BedrockPacketType::IDClientToServerHandshake => 0x04,
            BedrockPacketType::IDDisconnect => 0x05,
            BedrockPacketType::IDResourcePacksInfo => 0x06,
            BedrockPacketType::IDResourcePackStack => 0x07,
            BedrockPacketType::IDResourcePackClientResponse => 0x08,
            BedrockPacketType::IDText => 0x09,
            BedrockPacketType::IDSetTime => 0x0a,
            BedrockPacketType::IDStartGame => 0x0b,
            BedrockPacketType::IDAddPlayer => 0x0c,
            BedrockPacketType::IDAddActor => 0x0d,
            BedrockPacketType::IDRemoveActor => 0x0e,
            BedrockPacketType::IDAddItemActor => 0x0f,
            BedrockPacketType::IDServerPlayerPostMovePosition => 0x10,
            BedrockPacketType::IDTakeItemActor => 0x11,
            BedrockPacketType::IDMoveActorAbsolute => 0x12,
            BedrockPacketType::IDMovePlayer => 0x13,
            BedrockPacketType::IDUpdateBlock => 0x15,
            BedrockPacketType::IDAddPainting => 0x16,
            BedrockPacketType::IDLevelEvent => 0x19,
            BedrockPacketType::IDBlockEvent => 0x1a,
            BedrockPacketType::IDActorEvent => 0x1b,
            BedrockPacketType::IDMobEffect => 0x1c,
            BedrockPacketType::IDUpdateAttributes => 0x1d,
            BedrockPacketType::IDInventoryTransaction => 0x1e,
            BedrockPacketType::IDMobEquipment => 0x1f,
            BedrockPacketType::IDMobArmorEquipment => 0x20,
            BedrockPacketType::IDInteract => 0x21,
            BedrockPacketType::IDBlockPickRequest => 0x22,
            BedrockPacketType::IDActorPickRequest => 0x23,
            BedrockPacketType::IDPlayerAction => 0x24,
            BedrockPacketType::IDHurtArmor => 0x26,
            BedrockPacketType::IDSetActorData => 0x27,
            BedrockPacketType::IDSetActorMotion => 0x28,
            BedrockPacketType::IDSetActorLink => 0x29,
            BedrockPacketType::IDSetHealth => 0x2a,
            BedrockPacketType::IDSetSpawnPosition => 0x2b,
            BedrockPacketType::IDAnimate => 0x2c,
            BedrockPacketType::IDRespawn => 0x2d,
            BedrockPacketType::IDContainerOpen => 0x2e,
            BedrockPacketType::IDContainerClose => 0x2f,
            BedrockPacketType::IDPlayerHotbar => 0x30,
            BedrockPacketType::IDInventoryContent => 0x31,
            BedrockPacketType::IDInventorySlot => 0x32,
            BedrockPacketType::IDContainerSetData => 0x33,
            BedrockPacketType::IDCraftingData => 0x34,
            BedrockPacketType::IDGUIDataPickItem => 0x36,
            BedrockPacketType::IDBlockActorData => 0x38,
            BedrockPacketType::IDLevelChunk => 0x3a,
            BedrockPacketType::IDSetCommandsEnabled => 0x3b,
            BedrockPacketType::IDSetDifficulty => 0x3c,
            BedrockPacketType::IDChangeDimension => 0x3d,
            BedrockPacketType::IDSetPlayerGameType => 0x3e,
            BedrockPacketType::IDPlayerList => 0x3f,
            BedrockPacketType::IDSimpleEvent => 0x40,
            BedrockPacketType::IDLegacyTelemetryEvent => 0x41,
            BedrockPacketType::IDSpawnExperienceOrb => 0x42,
            BedrockPacketType::IDClientBoundMapItemData => 0x43,
            BedrockPacketType::IDMapInfoRequest => 0x44,
            BedrockPacketType::IDRequestChunkRadius => 0x45,
            BedrockPacketType::IDChunkRadiusUpdated => 0x46,
            BedrockPacketType::IDGameRulesChanged => 0x48,
            BedrockPacketType::IDCamera => 0x49,
            BedrockPacketType::IDBossEvent => 0x4a,
            BedrockPacketType::IDShowCredits => 0x4b,
            BedrockPacketType::IDAvailableCommands => 0x4c,
            BedrockPacketType::IDCommandRequest => 0x4d,
            BedrockPacketType::IDCommandBlockUpdate => 0x4e,
            BedrockPacketType::IDCommandOutput => 0x4f,
            BedrockPacketType::IDUpdateTrade => 0x50,
            BedrockPacketType::IDUpdateEquip => 0x51,
            BedrockPacketType::IDResourcePackDataInfo => 0x52,
            BedrockPacketType::IDResourcePackChunkData => 0x53,
            BedrockPacketType::IDResourcePackChunkRequest => 0x54,
            BedrockPacketType::IDTransfer => 0x55,
            BedrockPacketType::IDPlaySound => 0x56,
            BedrockPacketType::IDStopSound => 0x57,
            BedrockPacketType::IDSetTitle => 0x58,
            BedrockPacketType::IDAddBehaviorTree => 0x59,
            BedrockPacketType::IDStructureBlockUpdate => 0x5a,
            BedrockPacketType::IDShowStoreOffer => 0x5b,
            BedrockPacketType::IDPurchaseReceipt => 0x5c,
            BedrockPacketType::IDPlayerSkin => 0x5d,
            BedrockPacketType::IDSubClientLogin => 0x5e,
            BedrockPacketType::IDAutomationClientConnect => 0x5f,
            BedrockPacketType::IDSetLastHurtBy => 0x60,
            BedrockPacketType::IDBookEdit => 0x61,
            BedrockPacketType::IDNPCRequest => 0x62,
            BedrockPacketType::IDPhotoTransfer => 0x63,
            BedrockPacketType::IDModalFormRequest => 0x64,
            BedrockPacketType::IDModalFormResponse => 0x65,
            BedrockPacketType::IDServerSettingsRequest => 0x66,
            BedrockPacketType::IDServerSettingsResponse => 0x67,
            BedrockPacketType::IDShowProfile => 0x68,
            BedrockPacketType::IDSetDefaultGameType => 0x69,
            BedrockPacketType::IDRemoveObjective => 0x6a,
            BedrockPacketType::IDSetDisplayObjective => 0x6b,
            BedrockPacketType::IDSetScore => 0x6c,
            BedrockPacketType::IDLabTable => 0x6d,
            BedrockPacketType::IDUpdateBlockSynced => 0x6e,
            BedrockPacketType::IDMoveActorDelta => 0x6f,
            BedrockPacketType::IDSetScoreboardIdentity => 0x70,
            BedrockPacketType::IDSetLocalPlayerAsInitialized => 0x71,
            BedrockPacketType::IDUpdateSoftEnum => 0x72,
            BedrockPacketType::IDNetworkStackLatency => 0x73,
            BedrockPacketType::IDSpawnParticleEffect => 0x76,
            BedrockPacketType::IDAvailableActorIdentifiers => 0x77,
            BedrockPacketType::IDNetworkChunkPublisherUpdate => 0x79,
            BedrockPacketType::IDBiomeDefinitionList => 0x7a,
            BedrockPacketType::IDLevelSoundEvent => 0x7b,
            BedrockPacketType::IDLevelEventGeneric => 0x7c,
            BedrockPacketType::IDLecternUpdate => 0x7d,
            BedrockPacketType::IDClientCacheStatus => 0x81,
            BedrockPacketType::IDOnScreenTextureAnimation => 0x82,
            BedrockPacketType::IDMapCreateLockedCopy => 0x83,
            BedrockPacketType::IDStructureTemplateDataRequest => 0x84,
            BedrockPacketType::IDStructureTemplateDataResponse => 0x85,
            BedrockPacketType::IDClientCacheBlobStatus => 0x87,
            BedrockPacketType::IDClientCacheMissResponse => 0x88,
            BedrockPacketType::IDEducationSettings => 0x89,
            BedrockPacketType::IDEmote => 0x8a,
            BedrockPacketType::IDMultiplayerSettings => 0x8b,
            BedrockPacketType::IDSettingsCommand => 0x8c,
            BedrockPacketType::IDAnvilDamage => 0x8d,
            BedrockPacketType::IDCompletedUsingItem => 0x8e,
            BedrockPacketType::IDNetworkSettings => 0x8f,
            BedrockPacketType::IDPlayerAuthInput => 0x90,
            BedrockPacketType::IDCreativeContent => 0x91,
            BedrockPacketType::IDPlayerEnchantOptions => 0x92,
            BedrockPacketType::IDItemStackRequest => 0x93,
            BedrockPacketType::IDItemStackResponse => 0x94,
            BedrockPacketType::IDPlayerArmorDamage => 0x95,
            BedrockPacketType::IDCodeBuilder => 0x96,
            BedrockPacketType::IDUpdatePlayerGameType => 0x97,
            BedrockPacketType::IDEmoteList => 0x98,
            BedrockPacketType::IDPositionTrackingDBServerBroadcast => 0x99,
            BedrockPacketType::IDPositionTrackingDBClientRequest => 0x9a,
            BedrockPacketType::IDDebugInfo => 0x9b,
            BedrockPacketType::IDPacketViolationWarning => 0x9c,
            BedrockPacketType::IDMotionPredictionHints => 0x9d,
            BedrockPacketType::IDAnimateEntity => 0x9e,
            BedrockPacketType::IDCameraShake => 0x9f,
            BedrockPacketType::IDPlayerFog => 0xa0,
            BedrockPacketType::IDCorrectPlayerMovePrediction => 0xa1,
            BedrockPacketType::IDItemRegistry => 0xa2,
            BedrockPacketType::IDClientBoundDebugRenderer => 0xa4,
            BedrockPacketType::IDSyncActorProperty => 0xa5,
            BedrockPacketType::IDAddVolumeEntity => 0xa6,
            BedrockPacketType::IDRemoveVolumeEntity => 0xa7,
            BedrockPacketType::IDSimulationType => 0xa8,
            BedrockPacketType::IDNpcDialogue => 0xa9,
            BedrockPacketType::IDEduUriResource => 0xaa,
            BedrockPacketType::IDCreatePhoto => 0xab,
            BedrockPacketType::IDUpdateSubChunkBlocks => 0xac,
            BedrockPacketType::IDSubChunk => 0xae,
            BedrockPacketType::IDSubChunkRequest => 0xaf,
            BedrockPacketType::IDPlayerStartItemCooldown => 0xb0,
            BedrockPacketType::IDScriptMessage => 0xb1,
            BedrockPacketType::IDCodeBuilderSource => 0xb2,
            BedrockPacketType::IDTickingAreasLoadStatus => 0xb3,
            BedrockPacketType::IDDimensionData => 0xb4,
            BedrockPacketType::IDAgentActionEvent => 0xb5,
            BedrockPacketType::IDChangeMobProperty => 0xb6,
            BedrockPacketType::IDLessonProgress => 0xb7,
            BedrockPacketType::IDRequestAbility => 0xb8,
            BedrockPacketType::IDRequestPermissions => 0xb9,
            BedrockPacketType::IDToastRequest => 0xba,
            BedrockPacketType::IDUpdateAbilities => 0xbb,
            BedrockPacketType::IDUpdateAdventureSettings => 0xbc,
            BedrockPacketType::IDDeathInfo => 0xbd,
            BedrockPacketType::IDEditorNetwork => 0xbe,
            BedrockPacketType::IDFeatureRegistry => 0xbf,
            BedrockPacketType::IDServerStats => 0xc0,
            BedrockPacketType::IDRequestNetworkSettings => 0xc1,
            BedrockPacketType::IDGameTestRequest => 0xc2,
            BedrockPacketType::IDGameTestResults => 0xc3,
            BedrockPacketType::IDUpdateClientInputLocks => 0xc4,
            BedrockPacketType::IDCameraPresets => 0xc6,
            BedrockPacketType::IDUnlockedRecipes => 0xc7,
            BedrockPacketType::IDCameraInstruction => 0x12c,
            BedrockPacketType::IDTrimData => 0x12e,
            BedrockPacketType::IDOpenSign => 0x12f,
            BedrockPacketType::IDAgentAnimation => 0x130,
            BedrockPacketType::IDRefreshEntitlements => 0x131,
            BedrockPacketType::IDPlayerToggleCrafterSlotRequest => 0x132,
            BedrockPacketType::IDSetPlayerInventoryOptions => 0x133,
            BedrockPacketType::IDSetHud => 0x134,
            BedrockPacketType::IDAwardAchievement => 0x135,
            BedrockPacketType::IDClientBoundCloseForm => 0x136,
            BedrockPacketType::IDServerBoundLoadingScreen => 0x138,
            BedrockPacketType::IDJigsawStructureData => 0x139,
            BedrockPacketType::IDCurrentStructureFeature => 0x13a,
            BedrockPacketType::IDServerBoundDiagnostics => 0x13b,
            BedrockPacketType::IDCameraAimAssist => 0x13c,
            BedrockPacketType::IDContainerRegistryCleanup => 0x13d,
            BedrockPacketType::IDMovementEffect => 0x13e,
            BedrockPacketType::IDCameraAimAssistPresets => 0x140,
            BedrockPacketType::IDClientCameraAimAssist => 0x141,
            BedrockPacketType::IDClientMovementPredictionSync => 0x142,
            BedrockPacketType::IDUpdateClientOptions => 0x143,
            BedrockPacketType::IDPlayerVideoCapture => 0x144,
            BedrockPacketType::IDPlayerUpdateEntityOverrides => 0x145,
            BedrockPacketType::IDPlayerLocation => 0x146,
            BedrockPacketType::IDClientBoundControlSchemeSet => 0x147,
            BedrockPacketType::IDDebugDrawer => 0x148,
            BedrockPacketType::IDServerBoundPackSettingChange => 0x149,
            BedrockPacketType::IDClientBoundDataStore => 0x14a,
            BedrockPacketType::IDGraphicsOverrideParameter => 0x14b,
            BedrockPacketType::IDServerBoundDataStore => 0x14c,
            BedrockPacketType::IDClientBoundDataDrivenUIShowScreen => 0x14d,
            BedrockPacketType::IDClientBoundDataDrivenUICloseAllScreens => 0x14e,
            BedrockPacketType::IDClientBoundDataDrivenUIReload => 0x14f,
            BedrockPacketType::IDClientBoundTextureShift => 0x150,
            BedrockPacketType::IDVoxelShapes => 0x151,
            BedrockPacketType::IDCameraSpline => 0x152,
            BedrockPacketType::IDCameraAimAssistActorPriority => 0x153,
            _ => 0,
        }
    }
    pub fn get_packet_name(id: u16) -> &'static str {
        match id {
            0x01 => "Login",
            0x02 => "Play Status",
            0x03 => "Server To Client Handshake",
            0x04 => "Client To Server Handshake",
            0x05 => "Disconnect",
            0x06 => "Resource Packs Info",
            0x07 => "Resource Pack Stack",
            0x08 => "Resource Pack Client Response",
            0x09 => "Text",
            0x0a => "Set Time",
            0x0b => "Start Game",
            0x0c => "Add Player",
            0x0d => "Add Actor",
            0x0e => "Remove Actor",
            0x0f => "Add Item Actor",
            0x10 => "Server Player Post Move Position",
            0x11 => "Take Item Actor",
            0x12 => "Move Actor Absolute",
            0x13 => "Move Player",
            0x15 => "Update Block",
            0x16 => "Add Painting",
            0x19 => "Level Event",
            0x1a => "Block Event",
            0x1b => "Actor Event",
            0x1c => "Mob Effect",
            0x1d => "Update Attributes",
            0x1e => "Inventory Transaction",
            0x1f => "Mob Equipment",
            0x20 => "Mob Armor Equipment",
            0x21 => "Interact",
            0x22 => "Block Pick Request",
            0x23 => "Actor Pick Request",
            0x24 => "Player Action",
            0x26 => "Hurt Armor",
            0x27 => "Set Actor Data",
            0x28 => "Set Actor Motion",
            0x29 => "Set Actor Link",
            0x2a => "Set Health",
            0x2b => "Set Spawn Position",
            0x2c => "Animate",
            0x2d => "Respawn",
            0x2e => "Container Open",
            0x2f => "Container Close",
            0x30 => "Player Hotbar",
            0x31 => "Inventory Content",
            0x32 => "Inventory Slot",
            0x33 => "Container Set Data",
            0x34 => "Crafting Data",
            0x36 => "GUI Data Pick Item",
            0x38 => "Block Actor Data",
            0x3a => "Level Chunk",
            0x3b => "Set Commands Enabled",
            0x3c => "Set Difficulty",
            0x3d => "Change Dimension",
            0x3e => "Set Player Game Type",
            0x3f => "Player List",
            0x40 => "Simple Event",
            0x41 => "Legacy Telemetry Event",
            0x42 => "Spawn Experience Orb",
            0x43 => "Client Bound Map Item Data",
            0x44 => "Map Info Request",
            0x45 => "Request Chunk Radius",
            0x46 => "Chunk Radius Updated",
            0x48 => "Game Rules Changed",
            0x49 => "Camera",
            0x4a => "Boss Event",
            0x4b => "Show Credits",
            0x4c => "Available Commands",
            0x4d => "Command Request",
            0x4e => "Command Block Update",
            0x4f => "Command Output",
            0x50 => "Update Trade",
            0x51 => "Update Equip",
            0x52 => "Resource Pack Data Info",
            0x53 => "Resource Pack Chunk Data",
            0x54 => "Resource Pack Chunk Request",
            0x55 => "Transfer",
            0x56 => "Play Sound",
            0x57 => "Stop Sound",
            0x58 => "Set Title",
            0x59 => "Add Behavior Tree",
            0x5a => "Structure Block Update",
            0x5b => "Show Store Offer",
            0x5c => "Purchase Receipt",
            0x5d => "Player Skin",
            0x5e => "Sub Client Login",
            0x5f => "Automation Client Connect",
            0x60 => "Set Last Hurt By",
            0x61 => "Book Edit",
            0x62 => "NPC Request",
            0x63 => "Photo Transfer",
            0x64 => "Modal Form Request",
            0x65 => "Modal Form Response",
            0x66 => "Server Settings Request",
            0x67 => "Server Settings Response",
            0x68 => "Show Profile",
            0x69 => "Set Default Game Type",
            0x6a => "Remove Objective",
            0x6b => "Set Display Objective",
            0x6c => "Set Score",
            0x6d => "Lab Table",
            0x6e => "Update Block Synced",
            0x6f => "Move Actor Delta",
            0x70 => "Set Scoreboard Identity",
            0x71 => "Set Local Player As Initialized",
            0x72 => "Update Soft Enum",
            0x73 => "Network Stack Latency",
            0x76 => "Spawn Particle Event",
            0x77 => "Available Actor Identifiers",
            0x79 => "Network Chunk Publisher Update",
            0x7a => "Biome Definition List",
            0x7b => "Level Sound Event",
            0x7c => "Level Event Generic",
            0x7d => "Lectern Update",
            0x81 => "Client Cache Status",
            0x82 => "On Screen Texture Animation",
            0x83 => "Map Create Locked Copy",
            0x84 => "Structure Template Data Request",
            0x85 => "Structure Template Data Response",
            0x87 => "Client Cache Blob Status",
            0x88 => "Client Cache Miss Response",
            0x89 => "Education Settings",
            0x8a => "Emote",
            0x8b => "Multiplayer Settings",
            0x8c => "Settings Command",
            0x8d => "Anvil Damage",
            0x8e => "Completed Using Item",
            0x8f => "Network Settings",
            0x90 => "Player Auth Input",
            0x91 => "Creative Content",
            0x92 => "Player Enchant Options",
            0x93 => "Item Stack Request",
            0x94 => "Item Stack Response",
            0x95 => "Player Armor Damage",
            0x96 => "Code Builder",
            0x97 => "Update Player Game Type",
            0x98 => "Emote List",
            0x99 => "Position Tracking DB Server Broadcast",
            0x9a => "Position Tracking DB Client Request",
            0x9b => "Debug Info",
            0x9c => "Packet Violation Warning",
            0x9d => "Motion Prediction Hints",
            0x9e => "Animate Entity",
            0x9f => "Camera Shake",
            0xa0 => "Player Fog",
            0xa1 => "Correct Player Move Prediction",
            0xa2 => "Item Registry",
            0xa4 => "Client Bound Debug Renderer",
            0xa5 => "Sync Actor Property",
            0xa6 => "Add Volume Entity",
            0xa7 => "Remove Volume Entity",
            0xa8 => "Simulation Type",
            0xa9 => "Npc Dialogue",
            0xaa => "Edu Uri Resource",
            0xab => "Create Photo",
            0xac => "Update Sub Chunk Blocks",
            0xae => "Sub Chunk",
            0xaf => "Sub Chunk Request",
            0xb0 => "Player Start Item Cooldown",
            0xb1 => "Script Message",
            0xb2 => "Code Builder Source",
            0xb3 => "Ticking Areas Load Status",
            0xb4 => "Dimension Data",
            0xb5 => "Agent Action Event",
            0xb6 => "Change Mob Property",
            0xb7 => "Lesson Progress",
            0xb8 => "Request Ability",
            0xb9 => "Request Permissions",
            0xba => "Toast Request",
            0xbb => "Update Abilities",
            0xbc => "Update Adventure Settings",
            0xbd => "Death Info",
            0xbe => "Editor Network",
            0xbf => "Feature Registry",
            0xc0 => "Server Stats",
            0xc1 => "Request Network Settings",
            0xc2 => "Game Test Request",
            0xc3 => "Game Test Results",
            0xc4 => "Update Client Input Locks",
            0xc6 => "Camera Presets",
            0xc7 => "Unlocked Recipes",
            0x12c => "Camera Instruction",
            0x12e => "Trim Data",
            0x12f => "Open Sign",
            0x130 => "Agent Animation",
            0x131 => "Refresh Entitlements",
            0x132 => "Player Toggle Crafter Slot Request",
            0x133 => "Set Player Inventory Options",
            0x134 => "Set Hud",
            0x135 => "Award Achievement",
            0x136 => "Client Bound Close Form",
            0x138 => "Server Bound Loading Screen",
            0x139 => "Jigsaw Structure Data",
            0x13a => "Current Structure Feature",
            0x13b => "Server Bound Diagnostics",
            0x13c => "Camera Aim Assist",
            0x13d => "Container Registry Cleanup",
            0x13e => "Movement Effect",
            0x140 => "Camera Aim Assist Presets",
            0x141 => "Client Camera Aim Assist",
            0x142 => "Client Movement Prediction Sync",
            0x143 => "Update Client Options",
            0x144 => "Player Video Capture",
            0x145 => "Player Update Entity Overrides",
            0x146 => "Player Location",
            0x147 => "Client Bound Control Scheme Set",
            0x148 => "Server Script Debug Drawer",
            0x149 => "Server Bound Pack Setting Change",
            0x14a => "Client Bound Data Store",
            0x14b => "Graphics Override Parameter",
            0x14c => "Server Bound Data Store",
            0x14d => "Client Bound Data Driven UI Show Screen",
            0x14e => "Client Bound Data Driven UI Close All Screens",
            0x14f => "Client Bound Data Driven UI Reload",
            0x150 => "Client Bound Texture Shift",
            0x151 => "Voxel Shapes",
            0x152 => "Camera Spline",
            0x153 => "Camera Aim Assist Actor Priority",
            _ => "Unknown Packet",
        }
    }

    pub fn get_packet_from_id(id: u16, stream: &mut Stream) -> Box<dyn Packet> {
        match id {
            0x01 => Box::new(Login::decode(stream)),
            0x02 => Box::new(PlayStatus::decode(stream)),
            0x03 => Box::new(ServerToClientHandshake::decode(stream)),
            0x04 => Box::new(ClientToServerHandshake::decode(stream)),
            0x05 => Box::new(Disconnect::decode(stream)),
            0x06 => Box::new(ResourcePacksInfo::decode(stream)),
            0x07 => Box::new(ResourcePackStack::decode(stream)),
            0x08 => Box::new(ResourcePackClientResponse::decode(stream)),
            0x09 => Box::new(Text::decode(stream)),
            0x0a => Box::new(SetTime::decode(stream)),
            0x0b => Box::new(StartGame::decode(stream)),
            0x0c => Box::new(AddPlayer::decode(stream)),
            0x0d => Box::new(AddActor::decode(stream)),
            0x0e => Box::new(RemoveActor::decode(stream)),
            0x0f => Box::new(AddItemActor::decode(stream)),
            0x10 => Box::new(ServerPlayerPostMovePosition::decode(stream)),
            0x11 => Box::new(TakeItemActor::decode(stream)),
            0x12 => Box::new(MoveActorAbsolute::decode(stream)),
            0x13 => Box::new(MovePlayer::decode(stream)),
            0x15 => Box::new(UpdateBlock::decode(stream)),
            0x16 => Box::new(AddPainting::decode(stream)),
            0x19 => Box::new(LevelEvent::decode(stream)),
            0x1a => Box::new(BlockEvent::decode(stream)),
            0x1b => Box::new(ActorEvent::decode(stream)),
            0x1c => Box::new(MobEffect::decode(stream)),
            0x1d => Box::new(UpdateAttributes::decode(stream)),
            0x1e => Box::new(InventoryTransaction::decode(stream)),
            0x1f => Box::new(MobEquipment::decode(stream)),
            0x20 => Box::new(MobArmorEquipment::decode(stream)),
            0x21 => Box::new(Interact::decode(stream)),
            0x22 => Box::new(BlockPickRequest::decode(stream)),
            0x23 => Box::new(ActorPickRequest::decode(stream)),
            0x24 => Box::new(PlayerAction::decode(stream)),
            0x26 => Box::new(HurtArmor::decode(stream)),
            0x27 => Box::new(SetActorData::decode(stream)),
            0x28 => Box::new(SetActorMotion::decode(stream)),
            0x29 => Box::new(SetActorLink::decode(stream)),
            0x2a => Box::new(SetHealth::decode(stream)),
            0x2b => Box::new(SetSpawnPosition::decode(stream)),
            0x2c => Box::new(Animate::decode(stream)),
            0x2d => Box::new(Respawn::decode(stream)),
            0x2e => Box::new(ContainerOpen::decode(stream)),
            0x2f => Box::new(ContainerClose::decode(stream)),
            0x30 => Box::new(PlayerHotbar::decode(stream)),
            0x31 => Box::new(InventoryContent::decode(stream)),
            0x32 => Box::new(InventorySlot::decode(stream)),
            0x33 => Box::new(ContainerSetData::decode(stream)),
            0x34 => Box::new(CraftingData::decode(stream)),
            0x36 => Box::new(GUIDataPickItem::decode(stream)),
            0x38 => Box::new(BlockActorData::decode(stream)),
            0x3a => Box::new(LevelChunk::decode(stream)),
            0x3b => Box::new(SetCommandsEnabled::decode(stream)),
            0x3c => Box::new(SetDifficulty::decode(stream)),
            0x3d => Box::new(ChangeDimension::decode(stream)),
            0x3e => Box::new(SetPlayerGameType::decode(stream)),
            0x3f => Box::new(PlayerList::decode(stream)),
            0x40 => Box::new(SimpleEvent::decode(stream)),
            0x41 => Box::new(LegacyTelemetryEvent::decode(stream)),
            0x42 => Box::new(SpawnExperienceOrb::decode(stream)),
            0x43 => Box::new(ClientBoundMapItemData::decode(stream)),
            0x44 => Box::new(MapInfoRequest::decode(stream)),
            0x45 => Box::new(RequestChunkRadius::decode(stream)),
            0x46 => Box::new(ChunkRadiusUpdated::decode(stream)),
            0x48 => Box::new(GameRulesChanged::decode(stream)),
            0x49 => Box::new(Camera::decode(stream)),
            0x4a => Box::new(BossEvent::decode(stream)),
            0x4b => Box::new(ShowCredits::decode(stream)),
            0x4c => Box::new(AvailableCommands::decode(stream)),
            0x4d => Box::new(CommandRequest::decode(stream)),
            0x4e => Box::new(CommandBlockUpdate::decode(stream)),
            0x4f => Box::new(CommandOutput::decode(stream)),
            0x50 => Box::new(UpdateTrade::decode(stream)),
            0x51 => Box::new(UpdateEquip::decode(stream)),
            0x52 => Box::new(ResourcePackDataInfo::decode(stream)),
            0x53 => Box::new(ResourcePackChunkData::decode(stream)),
            0x54 => Box::new(ResourcePackChunkRequest::decode(stream)),
            0x55 => Box::new(Transfer::decode(stream)),
            0x56 => Box::new(PlaySound::decode(stream)),
            0x57 => Box::new(StopSound::decode(stream)),
            0x58 => Box::new(SetTitle::decode(stream)),
            0x59 => Box::new(AddBehaviorTree::decode(stream)),
            0x5a => Box::new(StructureBlockUpdate::decode(stream)),
            0x5b => Box::new(ShowStoreOffer::decode(stream)),
            0x5c => Box::new(PurchaseReceipt::decode(stream)),
            0x5d => Box::new(PlayerSkin::decode(stream)),
            0x5e => Box::new(SubClientLogin::decode(stream)),
            0x5f => Box::new(AutomationClientConnect::decode(stream)),
            0x60 => Box::new(SetLastHurtBy::decode(stream)),
            0x61 => Box::new(BookEdit::decode(stream)),
            0x62 => Box::new(NPCRequest::decode(stream)),
            0x63 => Box::new(PhotoTransfer::decode(stream)),
            0x64 => Box::new(ModalFormRequest::decode(stream)),
            0x65 => Box::new(ModalFormResponse::decode(stream)),
            0x66 => Box::new(ServerSettingsRequest::decode(stream)),
            0x67 => Box::new(ServerSettingsResponse::decode(stream)),
            0x68 => Box::new(ShowProfile::decode(stream)),
            0x69 => Box::new(SetDefaultGameType::decode(stream)),
            0x6a => Box::new(RemoveObjective::decode(stream)),
            0x6b => Box::new(SetDisplayObjective::decode(stream)),
            0x6c => Box::new(SetScore::decode(stream)),
            0x6d => Box::new(LabTable::decode(stream)),
            0x6e => Box::new(UpdateBlockSynced::decode(stream)),
            0x6f => Box::new(MoveActorDelta::decode(stream)),
            0x70 => Box::new(SetScoreboardIdentity::decode(stream)),
            0x71 => Box::new(SetLocalPlayerAsInitializedPacket::decode(stream)),
            0x72 => Box::new(UpdateSoftEnum::decode(stream)),
            0x73 => Box::new(NetworkStackLatency::decode(stream)),
            0x76 => Box::new(SpawnParticleEffect::decode(stream)),
            0x77 => Box::new(AvailableActorIdentifiers::decode(stream)),
            0x79 => Box::new(NetworkChunkPublisherUpdate::decode(stream)),
            0x7a => Box::new(BiomeDefinitionList::decode(stream)),
            0x7b => Box::new(LevelSoundEvent::decode(stream)),
            0x7c => Box::new(LevelEventGeneric::decode(stream)),
            0x7d => Box::new(LecternUpdate::decode(stream)),
            0x81 => Box::new(ClientCacheStatus::decode(stream)),
            0x82 => Box::new(OnScreenTextureAnimation::decode(stream)),
            0x83 => Box::new(MapCreateLockedCopy::decode(stream)),
            0x84 => Box::new(StructureTemplateDataRequest::decode(stream)),
            0x85 => Box::new(StructureTemplateDataResponse::decode(stream)),
            0x87 => Box::new(ClientCacheBlobStatus::decode(stream)),
            0x88 => Box::new(ClientCacheMissResponse::decode(stream)),
            0x89 => Box::new(EducationSettings::decode(stream)),
            0x8a => Box::new(Emote::decode(stream)),
            0x8b => Box::new(MultiplayerSettings::decode(stream)),
            0x8c => Box::new(SettingsCommand::decode(stream)),
            0x8d => Box::new(AnvilDamage::decode(stream)),
            0x8e => Box::new(CompletedUsingItem::decode(stream)),
            0x8f => Box::new(NetworkSettings::decode(stream)),
            0x90 => Box::new(PlayerAuthInput::decode(stream)),
            0x91 => Box::new(CreativeContent::decode(stream)),
            0x92 => Box::new(PlayerEnchantOptions::decode(stream)),
            0x93 => Box::new(ItemStackRequest::decode(stream)),
            0x94 => Box::new(ItemStackResponse::decode(stream)),
            0x95 => Box::new(PlayerArmorDamage::decode(stream)),
            0x96 => Box::new(CodeBuilder::decode(stream)),
            0x97 => Box::new(UpdatePlayerGameType::decode(stream)),
            0x98 => Box::new(EmoteList::decode(stream)),
            0x99 => Box::new(PositionTrackingDBServerBroadcast::decode(stream)),
            0x9a => Box::new(PositionTrackingDBClientRequest::decode(stream)),
            0x9b => Box::new(DebugInfo::decode(stream)),
            0x9c => Box::new(PacketViolationWarning::decode(stream)),
            0x9d => Box::new(MotionPredictionHints::decode(stream)),
            0x9e => Box::new(AnimateEntity::decode(stream)),
            0x9f => Box::new(CameraShake::decode(stream)),
            0xa0 => Box::new(PlayerFog::decode(stream)),
            0xa1 => Box::new(CorrectPlayerMovePrediction::decode(stream)),
            0xa2 => Box::new(ItemRegistry::decode(stream)),
            0xa4 => Box::new(ClientBoundDebugRenderer::decode(stream)),
            0xa5 => Box::new(SyncActorProperty::decode(stream)),
            0xa6 => Box::new(AddVolumeEntity::decode(stream)),
            0xa7 => Box::new(RemoveVolumeEntity::decode(stream)),
            0xa8 => Box::new(SimulationType::decode(stream)),
            0xa9 => Box::new(NPCDialogue::decode(stream)),
            0xaa => Box::new(EduUriResource::decode(stream)),
            0xab => Box::new(CreatePhoto::decode(stream)),
            0xac => Box::new(UpdateSubChunkBlocks::decode(stream)),
            0xae => Box::new(SubChunk::decode(stream)),
            0xaf => Box::new(SubChunkRequest::decode(stream)),
            0xb0 => Box::new(PlayerStartItemCooldown::decode(stream)),
            0xb1 => Box::new(ScriptMessage::decode(stream)),
            0xb2 => Box::new(CodeBuilderSource::decode(stream)),
            0xb3 => Box::new(TickingAreasLoadStatus::decode(stream)),
            0xb4 => Box::new(DimensionData::decode(stream)),
            0xb5 => Box::new(AgentActionEvent::decode(stream)),
            0xb6 => Box::new(ChangeMobProperty::decode(stream)),
            0xb7 => Box::new(LessonProgress::decode(stream)),
            0xb8 => Box::new(RequestAbility::decode(stream)),
            0xb9 => Box::new(RequestPermissions::decode(stream)),
            0xba => Box::new(ToastRequest::decode(stream)),
            0xbb => Box::new(UpdateAbilities::decode(stream)),
            0xbc => Box::new(UpdateAdventureSettings::decode(stream)),
            0xbd => Box::new(DeathInfo::decode(stream)),
            0xbe => Box::new(EditorNetwork::decode(stream)),
            0xbf => Box::new(FeatureRegistry::decode(stream)),
            0xc0 => Box::new(ServerStats::decode(stream)),
            0xc1 => Box::new(RequestNetworkSettings::decode(stream)),
            0xc2 => Box::new(GameTestRequest::decode(stream)),
            0xc3 => Box::new(GameTestResults::decode(stream)),
            0xc4 => Box::new(UpdateClientInputLocks::decode(stream)),
            0xc6 => Box::new(CameraPresets::decode(stream)),
            0xc7 => Box::new(UnlockedRecipes::decode(stream)),
            0x12c => Box::new(CameraInstruction::decode(stream)),
            0x12e => Box::new(TrimData::decode(stream)),
            0x12f => Box::new(OpenSign::decode(stream)),
            0x130 => Box::new(AgentAnimation::decode(stream)),
            0x131 => Box::new(RefreshEntitlements::decode(stream)),
            0x132 => Box::new(PlayerToggleCrafterSlotRequest::decode(stream)),
            0x133 => Box::new(SetPlayerInventoryOptions::decode(stream)),
            0x134 => Box::new(SetHud::decode(stream)),
            0x135 => Box::new(AwardAchievement::decode(stream)),
            0x136 => Box::new(ClientBoundCloseForm::decode(stream)),
            0x138 => Box::new(ServerBoundLoadingScreen::decode(stream)),
            0x139 => Box::new(JigsawStructureData::decode(stream)),
            0x13a => Box::new(CurrentStructureFeature::decode(stream)),
            0x13b => Box::new(ServerBoundDiagnostics::decode(stream)),
            0x13c => Box::new(CameraAimAssist::decode(stream)),
            0x13d => Box::new(ContainerRegistryCleanup::decode(stream)),
            0x13e => Box::new(MovementEffect::decode(stream)),
            0x140 => Box::new(CameraAimAssistPresets::decode(stream)),
            0x141 => Box::new(ClientCameraAimAssist::decode(stream)),
            0x142 => Box::new(ClientMovementPredictionSync::decode(stream)),
            0x143 => Box::new(UpdateClientOptions::decode(stream)),
            0x144 => Box::new(PlayerVideoCapture::decode(stream)),
            0x145 => Box::new(PlayerUpdateEntityOverrides::decode(stream)),
            0x146 => Box::new(PlayerLocation::decode(stream)),
            0x147 => Box::new(ClientBoundControlSchemeSet::decode(stream)),
            0x148 => Box::new(DebugDrawer::decode(stream)),
            0x149 => Box::new(ServerBoundPackSettingChange::decode(stream)),
            0x14a => Box::new(ClientBoundDataStore::decode(stream)),
            0x14b => Box::new(GraphicsOverrideParameter::decode(stream)),
            0x14c => Box::new(ServerBoundDataStore::decode(stream)),
            0x14d => Box::new(ClientBoundDataDrivenUIShowScreen::decode(stream)),
            0x14e => Box::new(ClientBoundDataDrivenUICloseAllScreens::decode(stream)),
            0x14f => Box::new(ClientBoundDataDrivenUIReload::decode(stream)),
            0x150 => Box::new(ClientBoundTextureShift::decode(stream)),
            0x151 => Box::new(VoxelShapes::decode(stream)),
            0x152 => Box::new(CameraSpline::decode(stream)),
            0x153 => Box::new(CameraAimAssistActorPriority::decode(stream)),
            _ => Box::new(Unknown::decode(stream)),
        }
    }
}
