use crate::protocol::bedrock::actor_event::ActorEvent;
use crate::protocol::bedrock::actor_pick_request::ActorPickRequest;
use crate::protocol::bedrock::add_actor::AddActor;
use crate::protocol::bedrock::add_behavior_tree::AddBehaviorTree;
use crate::protocol::bedrock::add_item_actor::AddItemActor;
use crate::protocol::bedrock::add_painting::AddPainting;
use crate::protocol::bedrock::add_player::AddPlayer;
use crate::protocol::bedrock::add_volume_entity::AddVolumeEntity;
use crate::protocol::bedrock::agent_action_event::AgentActionEvent;
use crate::protocol::bedrock::agent_animation::AgentAnimation;
use crate::protocol::bedrock::animate::Animate;
use crate::protocol::bedrock::animate_entity::AnimateEntity;
use crate::protocol::bedrock::anvil_damage::AnvilDamage;
use crate::protocol::bedrock::automation_client_connect::AutomationClientConnect;
use crate::protocol::bedrock::available_actor_identifiers::AvailableActorIdentifiers;
use crate::protocol::bedrock::available_commands::AvailableCommands;
use crate::protocol::bedrock::award_achievement::AwardAchievement;
use crate::protocol::bedrock::biome_definition_list::BiomeDefinitionList;
use crate::protocol::bedrock::block_actor_data::BlockActorData;
use crate::protocol::bedrock::block_event::BlockEvent;
use crate::protocol::bedrock::block_pick_request::BlockPickRequest;
use crate::protocol::bedrock::book_edit::BookEdit;
use crate::protocol::bedrock::boss_event::BossEvent;
use crate::protocol::bedrock::camera::Camera;
use crate::protocol::bedrock::camera_aim_assist::CameraAimAssist;
use crate::protocol::bedrock::camera_aim_assist_presets::CameraAimAssistPresets;
use crate::protocol::bedrock::camera_instruction::CameraInstruction;
use crate::protocol::bedrock::camera_presets::CameraPresets;
use crate::protocol::bedrock::camera_shake::CameraShake;
use crate::protocol::bedrock::change_dimension::ChangeDimension;
use crate::protocol::bedrock::change_mob_property::ChangeMobProperty;
use crate::protocol::bedrock::chunk_radius_updated::ChunkRadiusUpdated;
use crate::protocol::bedrock::client_bound_close_form::ClientBoundCloseForm;
use crate::protocol::bedrock::client_bound_control_scheme_set::ClientBoundControlSchemeSet;
use crate::protocol::bedrock::client_bound_data_store::ClientBoundDataStore;
use crate::protocol::bedrock::client_bound_debug_renderer::ClientBoundDebugRenderer;
use crate::protocol::bedrock::client_bound_map_item_data::ClientBoundMapItemData;
use crate::protocol::bedrock::client_cache_blob_status::ClientCacheBlobStatus;
use crate::protocol::bedrock::client_cache_miss_response::ClientCacheMissResponse;
use crate::protocol::bedrock::client_cache_status::ClientCacheStatus;
use crate::protocol::bedrock::client_camera_aim_assist::ClientCameraAimAssist;
use crate::protocol::bedrock::client_movement_prediction_sync::ClientMovementPredictionSync;
use crate::protocol::bedrock::client_to_server_handshake::ClientToServerHandshake;
use crate::protocol::bedrock::code_builder::CodeBuilder;
use crate::protocol::bedrock::code_builder_source::CodeBuilderSource;
use crate::protocol::bedrock::command_block_update::CommandBlockUpdate;
use crate::protocol::bedrock::command_output::CommandOutput;
use crate::protocol::bedrock::command_request::CommandRequest;
use crate::protocol::bedrock::completed_using_item::CompletedUsingItem;
use crate::protocol::bedrock::container_close::ContainerClose;
use crate::protocol::bedrock::container_open::ContainerOpen;
use crate::protocol::bedrock::container_registry_cleanup::ContainerRegistryCleanup;
use crate::protocol::bedrock::container_set_data::ContainerSetData;
use crate::protocol::bedrock::correct_player_move_prediction::CorrectPlayerMovePrediction;
use crate::protocol::bedrock::crafting_data::CraftingData;
use crate::protocol::bedrock::create_photo::CreatePhoto;
use crate::protocol::bedrock::creative_content::CreativeContent;
use crate::protocol::bedrock::current_structure_feature::CurrentStructureFeature;
use crate::protocol::bedrock::death_info::DeathInfo;
use crate::protocol::bedrock::primitive_shapes::PrimitiveShapes;
use crate::protocol::bedrock::debug_info::DebugInfo;
use crate::protocol::bedrock::dimension_data::DimensionData;
use crate::protocol::bedrock::disconnect::Disconnect;
use crate::protocol::bedrock::editor_network::EditorNetwork;
use crate::protocol::bedrock::edu_uri_resource::EduUriResource;
use crate::protocol::bedrock::education_settings::EducationSettings;
use crate::protocol::bedrock::emote::Emote;
use crate::protocol::bedrock::emote_list::EmoteList;
use crate::protocol::bedrock::feature_registry::FeatureRegistry;
use crate::protocol::bedrock::game_rules_changed::GameRulesChanged;
use crate::protocol::bedrock::game_test_request::GameTestRequest;
use crate::protocol::bedrock::game_test_results::GameTestResults;
use crate::protocol::bedrock::graphics_override_parameter::GraphicsOverrideParameter;
use crate::protocol::bedrock::gui_data_pick_item::GUIDataPickItem;
use crate::protocol::bedrock::hurt_armor::HurtArmor;
use crate::protocol::bedrock::interact::Interact;
use crate::protocol::bedrock::inventory_content::InventoryContent;
use crate::protocol::bedrock::inventory_slot::InventorySlot;
use crate::protocol::bedrock::inventory_transaction::InventoryTransaction;
use crate::protocol::bedrock::item_registry::ItemRegistry;
use crate::protocol::bedrock::item_stack_request::ItemStackRequest;
use crate::protocol::bedrock::item_stack_response::ItemStackResponse;
use crate::protocol::bedrock::jigsaw_structure_data::JigsawStructureData;
use crate::protocol::bedrock::lab_table::LabTable;
use crate::protocol::bedrock::lectern_update::LecternUpdate;
use crate::protocol::bedrock::legacy_telemetry_event::LegacyTelemetryEvent;
use crate::protocol::bedrock::lesson_progress::LessonProgress;
use crate::protocol::bedrock::level_chunk::LevelChunk;
use crate::protocol::bedrock::level_event::LevelEvent;
use crate::protocol::bedrock::level_event_generic::LevelEventGeneric;
use crate::protocol::bedrock::level_sound_event::LevelSoundEvent;
use crate::protocol::bedrock::login::Login;
use crate::protocol::bedrock::map_create_locked_copy::MapCreateLockedCopy;
use crate::protocol::bedrock::map_info_request::MapInfoRequest;
use crate::protocol::bedrock::mob_armor_equipment::MobArmorEquipment;
use crate::protocol::bedrock::mob_effect::MobEffect;
use crate::protocol::bedrock::mob_equipment::MobEquipment;
use crate::protocol::bedrock::modal_form_request::ModalFormRequest;
use crate::protocol::bedrock::modal_form_response::ModalFormResponse;
use crate::protocol::bedrock::motion_prediction_hints::MotionPredictionHints;
use crate::protocol::bedrock::move_actor_absolute::MoveActorAbsolute;
use crate::protocol::bedrock::move_actor_delta::MoveActorDelta;
use crate::protocol::bedrock::move_player::MovePlayer;
use crate::protocol::bedrock::movement_effect::MovementEffect;
use crate::protocol::bedrock::multiplayer_settings::MultiplayerSettings;
use crate::protocol::bedrock::network_chunk_publisher_update::NetworkChunkPublisherUpdate;
use crate::protocol::bedrock::network_settings::NetworkSettings;
use crate::protocol::bedrock::network_stack_latency::NetworkStackLatency;
use crate::protocol::bedrock::npc_dialogue::NPCDialogue;
use crate::protocol::bedrock::npc_request::NPCRequest;
use crate::protocol::bedrock::on_screen_texture_animation::OnScreenTextureAnimation;
use crate::protocol::bedrock::open_sign::OpenSign;
use crate::protocol::bedrock::packet::Packet;
use crate::protocol::bedrock::packet_violation_warning::PacketViolationWarning;
use crate::protocol::bedrock::photo_transfer::PhotoTransfer;
use crate::protocol::bedrock::play_sound::PlaySound;
use crate::protocol::bedrock::play_status::PlayStatus;
use crate::protocol::bedrock::player_action::PlayerAction;
use crate::protocol::bedrock::player_armor_damage::PlayerArmorDamage;
use crate::protocol::bedrock::player_auth_input::PlayerAuthInput;
use crate::protocol::bedrock::player_enchant_options::PlayerEnchantOptions;
use crate::protocol::bedrock::player_fog::PlayerFog;
use crate::protocol::bedrock::player_hotbar::PlayerHotbar;
use crate::protocol::bedrock::player_list::PlayerList;
use crate::protocol::bedrock::player_location::PlayerLocation;
use crate::protocol::bedrock::player_skin::PlayerSkin;
use crate::protocol::bedrock::player_start_item_cooldown::PlayerStartItemCooldown;
use crate::protocol::bedrock::player_toggle_crafter_slot_request::PlayerToggleCrafterSlotRequest;
use crate::protocol::bedrock::player_update_entity_overrides::PlayerUpdateEntityOverrides;
use crate::protocol::bedrock::player_video_capture::PlayerVideoCapture;
use crate::protocol::bedrock::position_tracking_db_client_request::PositionTrackingDBClientRequest;
use crate::protocol::bedrock::position_tracking_db_server_broadcast::PositionTrackingDBServerBroadcast;
use crate::protocol::bedrock::purchase_receipt::PurchaseReceipt;
use crate::protocol::bedrock::refresh_entitlements::RefreshEntitlements;
use crate::protocol::bedrock::remove_actor::RemoveActor;
use crate::protocol::bedrock::remove_objective::RemoveObjective;
use crate::protocol::bedrock::remove_volume_entity::RemoveVolumeEntity;
use crate::protocol::bedrock::req_network_settings::RequestNetworkSettings;
use crate::protocol::bedrock::request_ability::RequestAbility;
use crate::protocol::bedrock::request_chunk_radius::RequestChunkRadius;
use crate::protocol::bedrock::request_permissions::RequestPermissions;
use crate::protocol::bedrock::resource_pack_chunk_data::ResourcePackChunkData;
use crate::protocol::bedrock::resource_pack_chunk_request::ResourcePackChunkRequest;
use crate::protocol::bedrock::resource_pack_client_response::ResourcePackClientResponse;
use crate::protocol::bedrock::resource_pack_data_info::ResourcePackDataInfo;
use crate::protocol::bedrock::resource_pack_stack::ResourcePackStack;
use crate::protocol::bedrock::resource_packs_info::ResourcePacksInfo;
use crate::protocol::bedrock::respawn::Respawn;
use crate::protocol::bedrock::script_message::ScriptMessage;
use crate::protocol::bedrock::server_bound_data_store::ServerBoundDataStore;
use crate::protocol::bedrock::server_bound_diagnostics::ServerBoundDiagnostics;
use crate::protocol::bedrock::server_bound_loading_screen::ServerBoundLoadingScreen;
use crate::protocol::bedrock::server_bound_pack_setting_change::ServerBoundPackSettingChange;
use crate::protocol::bedrock::server_player_post_move_position::ServerPlayerPostMovePosition;
use crate::protocol::bedrock::server_settings_request::ServerSettingsRequest;
use crate::protocol::bedrock::server_settings_response::ServerSettingsResponse;
use crate::protocol::bedrock::server_stats::ServerStats;
use crate::protocol::bedrock::server_to_client_handshake::ServerToClientHandshake;
use crate::protocol::bedrock::set_actor_data::SetActorData;
use crate::protocol::bedrock::set_actor_link::SetActorLink;
use crate::protocol::bedrock::set_actor_motion::SetActorMotion;
use crate::protocol::bedrock::set_commands_enabled::SetCommandsEnabled;
use crate::protocol::bedrock::set_default_game_type::SetDefaultGameType;
use crate::protocol::bedrock::set_difficulty::SetDifficulty;
use crate::protocol::bedrock::set_display_objective::SetDisplayObjective;
use crate::protocol::bedrock::set_health::SetHealth;
use crate::protocol::bedrock::set_hud::SetHud;
use crate::protocol::bedrock::set_last_hurt_by::SetLastHurtBy;
use crate::protocol::bedrock::set_local_player_as_initialized::SetLocalPlayerAsInitializedPacket;
use crate::protocol::bedrock::set_player_game_type::SetPlayerGameType;
use crate::protocol::bedrock::set_player_inventory_options::SetPlayerInventoryOptions;
use crate::protocol::bedrock::set_score::SetScore;
use crate::protocol::bedrock::set_scoreboard_identity::SetScoreboardIdentity;
use crate::protocol::bedrock::set_spawn_position::SetSpawnPosition;
use crate::protocol::bedrock::set_time::SetTime;
use crate::protocol::bedrock::set_title::SetTitle;
use crate::protocol::bedrock::settings_command::SettingsCommand;
use crate::protocol::bedrock::show_credits::ShowCredits;
use crate::protocol::bedrock::show_profile::ShowProfile;
use crate::protocol::bedrock::show_store_offer::ShowStoreOffer;
use crate::protocol::bedrock::simple_event::SimpleEvent;
use crate::protocol::bedrock::simulation_type::SimulationType;
use crate::protocol::bedrock::spawn_experience_orb::SpawnExperienceOrb;
use crate::protocol::bedrock::spawn_particle_effect::SpawnParticleEffect;
use crate::protocol::bedrock::start_game::StartGame;
use crate::protocol::bedrock::stop_sound::StopSound;
use crate::protocol::bedrock::structure_block_update::StructureBlockUpdate;
use crate::protocol::bedrock::structure_template_data_request::StructureTemplateDataRequest;
use crate::protocol::bedrock::structure_template_data_response::StructureTemplateDataResponse;
use crate::protocol::bedrock::sub_chunk::SubChunk;
use crate::protocol::bedrock::sub_chunk_request::SubChunkRequest;
use crate::protocol::bedrock::sub_client_login::SubClientLogin;
use crate::protocol::bedrock::sync_actor_property::SyncActorProperty;
use crate::protocol::bedrock::take_item_actor::TakeItemActor;
use crate::protocol::bedrock::text::Text;
use crate::protocol::bedrock::ticking_areas_load_status::TickingAreasLoadStatus;
use crate::protocol::bedrock::toast_request::ToastRequest;
use crate::protocol::bedrock::transfer::Transfer;
use crate::protocol::bedrock::trim_data::TrimData;
use crate::protocol::bedrock::unknown::Unknown;
use crate::protocol::bedrock::unlocked_recipes::UnlockedRecipes;
use crate::protocol::bedrock::update_abilities::UpdateAbilities;
use crate::protocol::bedrock::update_adventure_settings::UpdateAdventureSettings;
use crate::protocol::bedrock::update_attributes::UpdateAttributes;
use crate::protocol::bedrock::update_block::UpdateBlock;
use crate::protocol::bedrock::update_block_synced::UpdateBlockSynced;
use crate::protocol::bedrock::update_client_input_locks::UpdateClientInputLocks;
use crate::protocol::bedrock::update_client_options::UpdateClientOptions;
use crate::protocol::bedrock::update_equip::UpdateEquip;
use crate::protocol::bedrock::update_player_game_type::UpdatePlayerGameType;
use crate::protocol::bedrock::update_soft_enum::UpdateSoftEnum;
use crate::protocol::bedrock::update_sub_chunk_blocks::UpdateSubChunkBlocks;
use crate::protocol::bedrock::update_trade::UpdateTrade;
use crate::protocol::bedrock::camera_aim_assist_actor_priority::CameraAimAssistActorPriority;
use crate::protocol::bedrock::camera_spline::CameraSpline;
use crate::protocol::bedrock::client_bound_data_driven_ui_close_screen::ClientBoundDataDrivenUICloseScreen;
use crate::protocol::bedrock::client_bound_data_driven_ui_reload::ClientBoundDataDrivenUIReload;
use crate::protocol::bedrock::client_bound_data_driven_ui_show_screen::ClientBoundDataDrivenUIShowScreen;
use crate::protocol::bedrock::client_bound_texture_shift::ClientBoundTextureShift;
use crate::protocol::bedrock::voxel_shapes::VoxelShapes;
use crate::protocol::bedrock::client_bound_attribute_layer_sync::ClientBoundAttributeLayerSync;
use crate::protocol::bedrock::locator_bar::LocatorBar;
use crate::protocol::bedrock::party_changed::PartyChanged;
use crate::protocol::bedrock::resource_packs_ready_for_validation::ResourcePacksReadyForValidation;
use crate::protocol::bedrock::server_bound_data_driven_screen_closed::ServerBoundDataDrivenScreenClosed;
use crate::protocol::bedrock::sync_world_clocks::SyncWorldClocks;
use crate::protocol::bedrock::server_presence_info::ServerPresenceInfo;
use crate::protocol::bedrock::server_store_info::ServerStoreInfo;
use binary_utils::binary::Stream;

#[repr(u16)]
pub enum BedrockPacketType {
    IDLogin,
    IDPlayStatus,
    IDServerToClientHandshake,
    IDClientToServerHandshake,
    IDDisconnect,
    IDResourcePacksInfo,
    IDResourcePackStack,
    IDResourcePackClientResponse,
    IDText,
    IDSetTime,
    IDStartGame,
    IDAddPlayer,
    IDAddActor,
    IDRemoveActor,
    IDAddItemActor,
    IDServerPlayerPostMovePosition,
    IDTakeItemActor,
    IDMoveActorAbsolute,
    IDMovePlayer,
    IDUpdateBlock,
    IDAddPainting,
    IDLevelSoundEventV1,
    IDLevelEvent,
    IDBlockEvent,
    IDActorEvent,
    IDMobEffect,
    IDUpdateAttributes,
    IDInventoryTransaction,
    IDMobEquipment,
    IDMobArmorEquipment,
    IDInteract,
    IDBlockPickRequest,
    IDActorPickRequest,
    IDPlayerAction,
    IDHurtArmor,
    IDSetActorData,
    IDSetActorMotion,
    IDSetActorLink,
    IDSetHealth,
    IDSetSpawnPosition,
    IDAnimate,
    IDRespawn,
    IDContainerOpen,
    IDContainerClose,
    IDPlayerHotbar,
    IDInventoryContent,
    IDInventorySlot,
    IDContainerSetData,
    IDCraftingData,
    IDGUIDataPickItem,
    IDBlockActorData,
    IDLevelChunk,
    IDSetCommandsEnabled,
    IDSetDifficulty,
    IDChangeDimension,
    IDSetPlayerGameType,
    IDPlayerList,
    IDSimpleEvent,
    IDLegacyTelemetryEvent,
    IDSpawnExperienceOrb,
    IDClientBoundMapItemData,
    IDMapInfoRequest,
    IDRequestChunkRadius,
    IDChunkRadiusUpdated,
    IDGameRulesChanged,
    IDCamera,
    IDBossEvent,
    IDShowCredits,
    IDAvailableCommands,
    IDCommandRequest,
    IDCommandBlockUpdate,
    IDCommandOutput,
    IDUpdateTrade,
    IDUpdateEquip,
    IDResourcePackDataInfo,
    IDResourcePackChunkData,
    IDResourcePackChunkRequest,
    IDTransfer,
    IDPlaySound,
    IDStopSound,
    IDSetTitle,
    IDAddBehaviorTree,
    IDStructureBlockUpdate,
    IDShowStoreOffer,
    IDPurchaseReceipt,
    IDPlayerSkin,
    IDSubClientLogin,
    IDAutomationClientConnect,
    IDSetLastHurtBy,
    IDBookEdit,
    IDNPCRequest,
    IDPhotoTransfer,
    IDModalFormRequest,
    IDModalFormResponse,
    IDServerSettingsRequest,
    IDServerSettingsResponse,
    IDShowProfile,
    IDSetDefaultGameType,
    IDRemoveObjective,
    IDSetDisplayObjective,
    IDSetScore,
    IDLabTable,
    IDUpdateBlockSynced,
    IDMoveActorDelta,
    IDSetScoreboardIdentity,
    IDSetLocalPlayerAsInitialized,
    IDUpdateSoftEnum,
    IDNetworkStackLatency,
    IDSpawnParticleEffect,
    IDAvailableActorIdentifiers,
    IDNetworkChunkPublisherUpdate,
    IDBiomeDefinitionList,
    IDLevelSoundEvent,
    IDLevelEventGeneric,
    IDLecternUpdate,
    IDClientCacheStatus,
    IDOnScreenTextureAnimation,
    IDMapCreateLockedCopy,
    IDStructureTemplateDataRequest,
    IDStructureTemplateDataResponse,
    IDClientCacheBlobStatus,
    IDClientCacheMissResponse,
    IDEducationSettings,
    IDEmote,
    IDMultiplayerSettings,
    IDSettingsCommand,
    IDAnvilDamage,
    IDCompletedUsingItem,
    IDNetworkSettings,
    IDPlayerAuthInput,
    IDCreativeContent,
    IDPlayerEnchantOptions,
    IDItemStackRequest,
    IDItemStackResponse,
    IDPlayerArmorDamage,
    IDCodeBuilder,
    IDUpdatePlayerGameType,
    IDEmoteList,
    IDPositionTrackingDBServerBroadcast,
    IDPositionTrackingDBClientRequest,
    IDDebugInfo,
    IDPacketViolationWarning,
    IDMotionPredictionHints,
    IDAnimateEntity,
    IDCameraShake,
    IDPlayerFog,
    IDCorrectPlayerMovePrediction,
    IDItemRegistry,
    IDClientBoundDebugRenderer,
    IDSyncActorProperty,
    IDAddVolumeEntity,
    IDRemoveVolumeEntity,
    IDSimulationType,
    IDNpcDialogue,
    IDEduUriResource,
    IDCreatePhoto,
    IDUpdateSubChunkBlocks,
    IDSubChunk,
    IDSubChunkRequest,
    IDPlayerStartItemCooldown,
    IDScriptMessage,
    IDCodeBuilderSource,
    IDTickingAreasLoadStatus,
    IDDimensionData,
    IDAgentActionEvent,
    IDChangeMobProperty,
    IDLessonProgress,
    IDRequestAbility,
    IDRequestPermissions,
    IDToastRequest,
    IDUpdateAbilities,
    IDUpdateAdventureSettings,
    IDDeathInfo,
    IDEditorNetwork,
    IDFeatureRegistry,
    IDServerStats,
    IDRequestNetworkSettings,
    IDGameTestRequest,
    IDGameTestResults,
    IDUpdateClientInputLocks,
    IDCameraPresets,
    IDUnlockedRecipes,
    IDCameraInstruction,
    IDTrimData,
    IDOpenSign,
    IDAgentAnimation,
    IDRefreshEntitlements,
    IDPlayerToggleCrafterSlotRequest,
    IDSetPlayerInventoryOptions,
    IDSetHud,
    IDAwardAchievement,
    IDClientBoundCloseForm,
    IDServerBoundLoadingScreen,
    IDJigsawStructureData,
    IDCurrentStructureFeature,
    IDServerBoundDiagnostics,
    IDCameraAimAssist,
    IDContainerRegistryCleanup,
    IDMovementEffect,
    IDCameraAimAssistPresets,
    IDClientCameraAimAssist,
    IDClientMovementPredictionSync,
    IDUpdateClientOptions,
    IDPlayerVideoCapture,
    IDPlayerUpdateEntityOverrides,
    IDPlayerLocation,
    IDClientBoundControlSchemeSet,
    IDPrimitiveShapes,
    IDServerBoundPackSettingChange,
    IDClientBoundDataStore,
    IDGraphicsOverrideParameter,
    IDServerBoundDataStore,
    IDClientBoundDataDrivenUIShowScreen,
    IDClientBoundDataDrivenUICloseScreen,
    IDClientBoundDataDrivenUIReload,
    IDClientBoundTextureShift,
    IDVoxelShapes,
    IDCameraSpline,
    IDCameraAimAssistActorPriority,
    IDResourcePacksReadyForValidation,
    IDLocatorBar,
    IDPartyChanged,
    IDServerBoundDataDrivenScreenClosed,
    IDSyncWorldClocks,
    IDClientBoundAttributeLayerSync,
    IDServerStoreInfo,
    IDServerPresenceInfo,
    IDUnknown,
}

impl BedrockPacketType {
    pub fn from_byte(byte: u16) -> Self {
        match byte {
            0x01 => BedrockPacketType::IDLogin,
            0x02 => BedrockPacketType::IDPlayStatus,
            0x03 => BedrockPacketType::IDServerToClientHandshake,
            0x04 => BedrockPacketType::IDClientToServerHandshake,
            0x05 => BedrockPacketType::IDDisconnect,
            0x06 => BedrockPacketType::IDResourcePacksInfo,
            0x07 => BedrockPacketType::IDResourcePackStack,
            0x08 => BedrockPacketType::IDResourcePackClientResponse,
            0x09 => BedrockPacketType::IDText,
            0x0a => BedrockPacketType::IDSetTime,
            0x0b => BedrockPacketType::IDStartGame,
            0x0c => BedrockPacketType::IDAddPlayer,
            0x0d => BedrockPacketType::IDAddActor,
            0x0e => BedrockPacketType::IDRemoveActor,
            0x0f => BedrockPacketType::IDAddItemActor,
            0x10 => BedrockPacketType::IDServerPlayerPostMovePosition,
            0x11 => BedrockPacketType::IDTakeItemActor,
            0x12 => BedrockPacketType::IDMoveActorAbsolute,
            0x13 => BedrockPacketType::IDMovePlayer,
            0x15 => BedrockPacketType::IDUpdateBlock,
            0x16 => BedrockPacketType::IDAddPainting,
            0x19 => BedrockPacketType::IDLevelEvent,
            0x1a => BedrockPacketType::IDBlockEvent,
            0x1b => BedrockPacketType::IDActorEvent,
            0x1c => BedrockPacketType::IDMobEffect,
            0x1d => BedrockPacketType::IDUpdateAttributes,
            0x1e => BedrockPacketType::IDInventoryTransaction,
            0x1f => BedrockPacketType::IDMobEquipment,
            0x20 => BedrockPacketType::IDMobArmorEquipment,
            0x21 => BedrockPacketType::IDInteract,
            0x22 => BedrockPacketType::IDBlockPickRequest,
            0x23 => BedrockPacketType::IDActorPickRequest,
            0x24 => BedrockPacketType::IDPlayerAction,
            0x26 => BedrockPacketType::IDHurtArmor,
            0x27 => BedrockPacketType::IDSetActorData,
            0x28 => BedrockPacketType::IDSetActorMotion,
            0x29 => BedrockPacketType::IDSetActorLink,
            0x2a => BedrockPacketType::IDSetHealth,
            0x2b => BedrockPacketType::IDSetSpawnPosition,
            0x2c => BedrockPacketType::IDAnimate,
            0x2d => BedrockPacketType::IDRespawn,
            0x2e => BedrockPacketType::IDContainerOpen,
            0x2f => BedrockPacketType::IDContainerClose,
            0x30 => BedrockPacketType::IDPlayerHotbar,
            0x31 => BedrockPacketType::IDInventoryContent,
            0x32 => BedrockPacketType::IDInventorySlot,
            0x33 => BedrockPacketType::IDContainerSetData,
            0x34 => BedrockPacketType::IDCraftingData,
            0x36 => BedrockPacketType::IDGUIDataPickItem,
            0x38 => BedrockPacketType::IDBlockActorData,
            0x3a => BedrockPacketType::IDLevelChunk,
            0x3b => BedrockPacketType::IDSetCommandsEnabled,
            0x3c => BedrockPacketType::IDSetDifficulty,
            0x3d => BedrockPacketType::IDChangeDimension,
            0x3e => BedrockPacketType::IDSetPlayerGameType,
            0x3f => BedrockPacketType::IDPlayerList,
            0x40 => BedrockPacketType::IDSimpleEvent,
            0x41 => BedrockPacketType::IDLegacyTelemetryEvent,
            0x42 => BedrockPacketType::IDSpawnExperienceOrb,
            0x43 => BedrockPacketType::IDClientBoundMapItemData,
            0x44 => BedrockPacketType::IDMapInfoRequest,
            0x45 => BedrockPacketType::IDRequestChunkRadius,
            0x46 => BedrockPacketType::IDChunkRadiusUpdated,
            0x48 => BedrockPacketType::IDGameRulesChanged,
            0x49 => BedrockPacketType::IDCamera,
            0x4a => BedrockPacketType::IDBossEvent,
            0x4b => BedrockPacketType::IDShowCredits,
            0x4c => BedrockPacketType::IDAvailableCommands,
            0x4d => BedrockPacketType::IDCommandRequest,
            0x4e => BedrockPacketType::IDCommandBlockUpdate,
            0x4f => BedrockPacketType::IDCommandOutput,
            0x50 => BedrockPacketType::IDUpdateTrade,
            0x51 => BedrockPacketType::IDUpdateEquip,
            0x52 => BedrockPacketType::IDResourcePackDataInfo,
            0x53 => BedrockPacketType::IDResourcePackChunkData,
            0x54 => BedrockPacketType::IDResourcePackChunkRequest,
            0x55 => BedrockPacketType::IDTransfer,
            0x56 => BedrockPacketType::IDPlaySound,
            0x57 => BedrockPacketType::IDStopSound,
            0x58 => BedrockPacketType::IDSetTitle,
            0x59 => BedrockPacketType::IDAddBehaviorTree,
            0x5a => BedrockPacketType::IDStructureBlockUpdate,
            0x5b => BedrockPacketType::IDShowStoreOffer,
            0x5c => BedrockPacketType::IDPurchaseReceipt,
            0x5d => BedrockPacketType::IDPlayerSkin,
            0x5e => BedrockPacketType::IDSubClientLogin,
            0x5f => BedrockPacketType::IDAutomationClientConnect,
            0x60 => BedrockPacketType::IDSetLastHurtBy,
            0x61 => BedrockPacketType::IDBookEdit,
            0x62 => BedrockPacketType::IDNPCRequest,
            0x63 => BedrockPacketType::IDPhotoTransfer,
            0x64 => BedrockPacketType::IDModalFormRequest,
            0x65 => BedrockPacketType::IDModalFormResponse,
            0x66 => BedrockPacketType::IDServerSettingsRequest,
            0x67 => BedrockPacketType::IDServerSettingsResponse,
            0x68 => BedrockPacketType::IDShowProfile,
            0x69 => BedrockPacketType::IDSetDefaultGameType,
            0x6a => BedrockPacketType::IDRemoveObjective,
            0x6b => BedrockPacketType::IDSetDisplayObjective,
            0x6c => BedrockPacketType::IDSetScore,
            0x6d => BedrockPacketType::IDLabTable,
            0x6e => BedrockPacketType::IDUpdateBlockSynced,
            0x6f => BedrockPacketType::IDMoveActorDelta,
            0x70 => BedrockPacketType::IDSetScoreboardIdentity,
            0x71 => BedrockPacketType::IDSetLocalPlayerAsInitialized,
            0x72 => BedrockPacketType::IDUpdateSoftEnum,
            0x73 => BedrockPacketType::IDNetworkStackLatency,
            0x76 => BedrockPacketType::IDSpawnParticleEffect,
            0x77 => BedrockPacketType::IDAvailableActorIdentifiers,
            0x79 => BedrockPacketType::IDNetworkChunkPublisherUpdate,
            0x7a => BedrockPacketType::IDBiomeDefinitionList,
            0x7b => BedrockPacketType::IDLevelSoundEvent,
            0x7c => BedrockPacketType::IDLevelEventGeneric,
            0x7d => BedrockPacketType::IDLecternUpdate,
            0x81 => BedrockPacketType::IDClientCacheStatus,
            0x82 => BedrockPacketType::IDOnScreenTextureAnimation,
            0x83 => BedrockPacketType::IDMapCreateLockedCopy,
            0x84 => BedrockPacketType::IDStructureTemplateDataRequest,
            0x85 => BedrockPacketType::IDStructureTemplateDataResponse,
            0x87 => BedrockPacketType::IDClientCacheBlobStatus,
            0x88 => BedrockPacketType::IDClientCacheMissResponse,
            0x89 => BedrockPacketType::IDEducationSettings,
            0x8a => BedrockPacketType::IDEmote,
            0x8b => BedrockPacketType::IDMultiplayerSettings,
            0x8c => BedrockPacketType::IDSettingsCommand,
            0x8d => BedrockPacketType::IDAnvilDamage,
            0x8e => BedrockPacketType::IDCompletedUsingItem,
            0x8f => BedrockPacketType::IDNetworkSettings,
            0x90 => BedrockPacketType::IDPlayerAuthInput,
            0x91 => BedrockPacketType::IDCreativeContent,
            0x92 => BedrockPacketType::IDPlayerEnchantOptions,
            0x93 => BedrockPacketType::IDItemStackRequest,
            0x94 => BedrockPacketType::IDItemStackResponse,
            0x95 => BedrockPacketType::IDPlayerArmorDamage,
            0x96 => BedrockPacketType::IDCodeBuilder,
            0x97 => BedrockPacketType::IDUpdatePlayerGameType,
            0x98 => BedrockPacketType::IDEmoteList,
            0x99 => BedrockPacketType::IDPositionTrackingDBServerBroadcast,
            0x9a => BedrockPacketType::IDPositionTrackingDBClientRequest,
            0x9b => BedrockPacketType::IDDebugInfo,
            0x9c => BedrockPacketType::IDPacketViolationWarning,
            0x9d => BedrockPacketType::IDMotionPredictionHints,
            0x9e => BedrockPacketType::IDAnimateEntity,
            0x9f => BedrockPacketType::IDCameraShake,
            0xa0 => BedrockPacketType::IDPlayerFog,
            0xa1 => BedrockPacketType::IDCorrectPlayerMovePrediction,
            0xa2 => BedrockPacketType::IDItemRegistry,
            0xa4 => BedrockPacketType::IDClientBoundDebugRenderer,
            0xa5 => BedrockPacketType::IDSyncActorProperty,
            0xa6 => BedrockPacketType::IDAddVolumeEntity,
            0xa7 => BedrockPacketType::IDRemoveVolumeEntity,
            0xa8 => BedrockPacketType::IDSimulationType,
            0xa9 => BedrockPacketType::IDNpcDialogue,
            0xaa => BedrockPacketType::IDEduUriResource,
            0xab => BedrockPacketType::IDCreatePhoto,
            0xac => BedrockPacketType::IDUpdateSubChunkBlocks,
            0xae => BedrockPacketType::IDSubChunk,
            0xaf => BedrockPacketType::IDSubChunkRequest,
            0xb0 => BedrockPacketType::IDPlayerStartItemCooldown,
            0xb1 => BedrockPacketType::IDScriptMessage,
            0xb2 => BedrockPacketType::IDCodeBuilderSource,
            0xb3 => BedrockPacketType::IDTickingAreasLoadStatus,
            0xb4 => BedrockPacketType::IDDimensionData,
            0xb5 => BedrockPacketType::IDAgentActionEvent,
            0xb6 => BedrockPacketType::IDChangeMobProperty,
            0xb7 => BedrockPacketType::IDLessonProgress,
            0xb8 => BedrockPacketType::IDRequestAbility,
            0xb9 => BedrockPacketType::IDRequestPermissions,
            0xba => BedrockPacketType::IDToastRequest,
            0xbb => BedrockPacketType::IDUpdateAbilities,
            0xbc => BedrockPacketType::IDUpdateAdventureSettings,
            0xbd => BedrockPacketType::IDDeathInfo,
            0xbe => BedrockPacketType::IDEditorNetwork,
            0xbf => BedrockPacketType::IDFeatureRegistry,
            0xc0 => BedrockPacketType::IDServerStats,
            0xc1 => BedrockPacketType::IDRequestNetworkSettings,
            0xc2 => BedrockPacketType::IDGameTestRequest,
            0xc3 => BedrockPacketType::IDGameTestResults,
            0xc4 => BedrockPacketType::IDUpdateClientInputLocks,
            0xc6 => BedrockPacketType::IDCameraPresets,
            0xc7 => BedrockPacketType::IDUnlockedRecipes,
            0x12c => BedrockPacketType::IDCameraInstruction,
            0x12e => BedrockPacketType::IDTrimData,
            0x12f => BedrockPacketType::IDOpenSign,
            0x130 => BedrockPacketType::IDAgentAnimation,
            0x131 => BedrockPacketType::IDRefreshEntitlements,
            0x132 => BedrockPacketType::IDPlayerToggleCrafterSlotRequest,
            0x133 => BedrockPacketType::IDSetPlayerInventoryOptions,
            0x134 => BedrockPacketType::IDSetHud,
            0x135 => BedrockPacketType::IDAwardAchievement,
            0x136 => BedrockPacketType::IDClientBoundCloseForm,
            0x138 => BedrockPacketType::IDServerBoundLoadingScreen,
            0x139 => BedrockPacketType::IDJigsawStructureData,
            0x13a => BedrockPacketType::IDCurrentStructureFeature,
            0x13b => BedrockPacketType::IDServerBoundDiagnostics,
            0x13c => BedrockPacketType::IDCameraAimAssist,
            0x13d => BedrockPacketType::IDContainerRegistryCleanup,
            0x13e => BedrockPacketType::IDMovementEffect,
            0x140 => BedrockPacketType::IDCameraAimAssistPresets,
            0x141 => BedrockPacketType::IDClientCameraAimAssist,
            0x142 => BedrockPacketType::IDClientMovementPredictionSync,
            0x143 => BedrockPacketType::IDUpdateClientOptions,
            0x144 => BedrockPacketType::IDPlayerVideoCapture,
            0x145 => BedrockPacketType::IDPlayerUpdateEntityOverrides,
            0x146 => BedrockPacketType::IDPlayerLocation,
            0x147 => BedrockPacketType::IDClientBoundControlSchemeSet,
            0x148 => BedrockPacketType::IDPrimitiveShapes,
            0x149 => BedrockPacketType::IDServerBoundPackSettingChange,
            0x14a => BedrockPacketType::IDClientBoundDataStore,
            0x14b => BedrockPacketType::IDGraphicsOverrideParameter,
            0x14c => BedrockPacketType::IDServerBoundDataStore,
            0x14d => BedrockPacketType::IDClientBoundDataDrivenUIShowScreen,
            0x14e => BedrockPacketType::IDClientBoundDataDrivenUICloseScreen,
            0x14f => BedrockPacketType::IDClientBoundDataDrivenUIReload,
            0x150 => BedrockPacketType::IDClientBoundTextureShift,
            0x151 => BedrockPacketType::IDVoxelShapes,
            0x152 => BedrockPacketType::IDCameraSpline,
            0x153 => BedrockPacketType::IDCameraAimAssistActorPriority,
            0x154 => BedrockPacketType::IDResourcePacksReadyForValidation,
            0x155 => BedrockPacketType::IDLocatorBar,
            0x156 => BedrockPacketType::IDPartyChanged,
            0x157 => BedrockPacketType::IDServerBoundDataDrivenScreenClosed,
            0x158 => BedrockPacketType::IDSyncWorldClocks,
            0x159 => BedrockPacketType::IDClientBoundAttributeLayerSync,
            0x15a => BedrockPacketType::IDServerStoreInfo,
            0x15b => BedrockPacketType::IDServerPresenceInfo,
            _ => BedrockPacketType::IDUnknown,
        }
    }
    pub fn get_byte(self) -> u16 {
        match self {
            BedrockPacketType::IDLogin => 0x01,
            BedrockPacketType::IDPlayStatus => 0x02,
            BedrockPacketType::IDServerToClientHandshake => 0x03,
            BedrockPacketType::IDClientToServerHandshake => 0x04,
            BedrockPacketType::IDDisconnect => 0x05,
            BedrockPacketType::IDResourcePacksInfo => 0x06,
            BedrockPacketType::IDResourcePackStack => 0x07,
            BedrockPacketType::IDResourcePackClientResponse => 0x08,
            BedrockPacketType::IDText => 0x09,
            BedrockPacketType::IDSetTime => 0x0a,
            BedrockPacketType::IDStartGame => 0x0b,
            BedrockPacketType::IDAddPlayer => 0x0c,
            BedrockPacketType::IDAddActor => 0x0d,
            BedrockPacketType::IDRemoveActor => 0x0e,
            BedrockPacketType::IDAddItemActor => 0x0f,
            BedrockPacketType::IDServerPlayerPostMovePosition => 0x10,
            BedrockPacketType::IDTakeItemActor => 0x11,
            BedrockPacketType::IDMoveActorAbsolute => 0x12,
            BedrockPacketType::IDMovePlayer => 0x13,
            BedrockPacketType::IDUpdateBlock => 0x15,
            BedrockPacketType::IDAddPainting => 0x16,
            BedrockPacketType::IDLevelEvent => 0x19,
            BedrockPacketType::IDBlockEvent => 0x1a,
            BedrockPacketType::IDActorEvent => 0x1b,
            BedrockPacketType::IDMobEffect => 0x1c,
            BedrockPacketType::IDUpdateAttributes => 0x1d,
            BedrockPacketType::IDInventoryTransaction => 0x1e,
            BedrockPacketType::IDMobEquipment => 0x1f,
            BedrockPacketType::IDMobArmorEquipment => 0x20,
            BedrockPacketType::IDInteract => 0x21,
            BedrockPacketType::IDBlockPickRequest => 0x22,
            BedrockPacketType::IDActorPickRequest => 0x23,
            BedrockPacketType::IDPlayerAction => 0x24,
            BedrockPacketType::IDHurtArmor => 0x26,
            BedrockPacketType::IDSetActorData => 0x27,
            BedrockPacketType::IDSetActorMotion => 0x28,
            BedrockPacketType::IDSetActorLink => 0x29,
            BedrockPacketType::IDSetHealth => 0x2a,
            BedrockPacketType::IDSetSpawnPosition => 0x2b,
            BedrockPacketType::IDAnimate => 0x2c,
            BedrockPacketType::IDRespawn => 0x2d,
            BedrockPacketType::IDContainerOpen => 0x2e,
            BedrockPacketType::IDContainerClose => 0x2f,
            BedrockPacketType::IDPlayerHotbar => 0x30,
            BedrockPacketType::IDInventoryContent => 0x31,
            BedrockPacketType::IDInventorySlot => 0x32,
            BedrockPacketType::IDContainerSetData => 0x33,
            BedrockPacketType::IDCraftingData => 0x34,
            BedrockPacketType::IDGUIDataPickItem => 0x36,
            BedrockPacketType::IDBlockActorData => 0x38,
            BedrockPacketType::IDLevelChunk => 0x3a,
            BedrockPacketType::IDSetCommandsEnabled => 0x3b,
            BedrockPacketType::IDSetDifficulty => 0x3c,
            BedrockPacketType::IDChangeDimension => 0x3d,
            BedrockPacketType::IDSetPlayerGameType => 0x3e,
            BedrockPacketType::IDPlayerList => 0x3f,
            BedrockPacketType::IDSimpleEvent => 0x40,
            BedrockPacketType::IDLegacyTelemetryEvent => 0x41,
            BedrockPacketType::IDSpawnExperienceOrb => 0x42,
            BedrockPacketType::IDClientBoundMapItemData => 0x43,
            BedrockPacketType::IDMapInfoRequest => 0x44,
            BedrockPacketType::IDRequestChunkRadius => 0x45,
            BedrockPacketType::IDChunkRadiusUpdated => 0x46,
            BedrockPacketType::IDGameRulesChanged => 0x48,
            BedrockPacketType::IDCamera => 0x49,
            BedrockPacketType::IDBossEvent => 0x4a,
            BedrockPacketType::IDShowCredits => 0x4b,
            BedrockPacketType::IDAvailableCommands => 0x4c,
            BedrockPacketType::IDCommandRequest => 0x4d,
            BedrockPacketType::IDCommandBlockUpdate => 0x4e,
            BedrockPacketType::IDCommandOutput => 0x4f,
            BedrockPacketType::IDUpdateTrade => 0x50,
            BedrockPacketType::IDUpdateEquip => 0x51,
            BedrockPacketType::IDResourcePackDataInfo => 0x52,
            BedrockPacketType::IDResourcePackChunkData => 0x53,
            BedrockPacketType::IDResourcePackChunkRequest => 0x54,
            BedrockPacketType::IDTransfer => 0x55,
            BedrockPacketType::IDPlaySound => 0x56,
            BedrockPacketType::IDStopSound => 0x57,
            BedrockPacketType::IDSetTitle => 0x58,
            BedrockPacketType::IDAddBehaviorTree => 0x59,
            BedrockPacketType::IDStructureBlockUpdate => 0x5a,
            BedrockPacketType::IDShowStoreOffer => 0x5b,
            BedrockPacketType::IDPurchaseReceipt => 0x5c,
            BedrockPacketType::IDPlayerSkin => 0x5d,
            BedrockPacketType::IDSubClientLogin => 0x5e,
            BedrockPacketType::IDAutomationClientConnect => 0x5f,
            BedrockPacketType::IDSetLastHurtBy => 0x60,
            BedrockPacketType::IDBookEdit => 0x61,
            BedrockPacketType::IDNPCRequest => 0x62,
            BedrockPacketType::IDPhotoTransfer => 0x63,
            BedrockPacketType::IDModalFormRequest => 0x64,
            BedrockPacketType::IDModalFormResponse => 0x65,
            BedrockPacketType::IDServerSettingsRequest => 0x66,
            BedrockPacketType::IDServerSettingsResponse => 0x67,
            BedrockPacketType::IDShowProfile => 0x68,
            BedrockPacketType::IDSetDefaultGameType => 0x69,
            BedrockPacketType::IDRemoveObjective => 0x6a,
            BedrockPacketType::IDSetDisplayObjective => 0x6b,
            BedrockPacketType::IDSetScore => 0x6c,
            BedrockPacketType::IDLabTable => 0x6d,
            BedrockPacketType::IDUpdateBlockSynced => 0x6e,
            BedrockPacketType::IDMoveActorDelta => 0x6f,
            BedrockPacketType::IDSetScoreboardIdentity => 0x70,
            BedrockPacketType::IDSetLocalPlayerAsInitialized => 0x71,
            BedrockPacketType::IDUpdateSoftEnum => 0x72,
            BedrockPacketType::IDNetworkStackLatency => 0x73,
            BedrockPacketType::IDSpawnParticleEffect => 0x76,
            BedrockPacketType::IDAvailableActorIdentifiers => 0x77,
            BedrockPacketType::IDNetworkChunkPublisherUpdate => 0x79,
            BedrockPacketType::IDBiomeDefinitionList => 0x7a,
            BedrockPacketType::IDLevelSoundEvent => 0x7b,
            BedrockPacketType::IDLevelEventGeneric => 0x7c,
            BedrockPacketType::IDLecternUpdate => 0x7d,
            BedrockPacketType::IDClientCacheStatus => 0x81,
            BedrockPacketType::IDOnScreenTextureAnimation => 0x82,
            BedrockPacketType::IDMapCreateLockedCopy => 0x83,
            BedrockPacketType::IDStructureTemplateDataRequest => 0x84,
            BedrockPacketType::IDStructureTemplateDataResponse => 0x85,
            BedrockPacketType::IDClientCacheBlobStatus => 0x87,
            BedrockPacketType::IDClientCacheMissResponse => 0x88,
            BedrockPacketType::IDEducationSettings => 0x89,
            BedrockPacketType::IDEmote => 0x8a,
            BedrockPacketType::IDMultiplayerSettings => 0x8b,
            BedrockPacketType::IDSettingsCommand => 0x8c,
            BedrockPacketType::IDAnvilDamage => 0x8d,
            BedrockPacketType::IDCompletedUsingItem => 0x8e,
            BedrockPacketType::IDNetworkSettings => 0x8f,
            BedrockPacketType::IDPlayerAuthInput => 0x90,
            BedrockPacketType::IDCreativeContent => 0x91,
            BedrockPacketType::IDPlayerEnchantOptions => 0x92,
            BedrockPacketType::IDItemStackRequest => 0x93,
            BedrockPacketType::IDItemStackResponse => 0x94,
            BedrockPacketType::IDPlayerArmorDamage => 0x95,
            BedrockPacketType::IDCodeBuilder => 0x96,
            BedrockPacketType::IDUpdatePlayerGameType => 0x97,
            BedrockPacketType::IDEmoteList => 0x98,
            BedrockPacketType::IDPositionTrackingDBServerBroadcast => 0x99,
            BedrockPacketType::IDPositionTrackingDBClientRequest => 0x9a,
            BedrockPacketType::IDDebugInfo => 0x9b,
            BedrockPacketType::IDPacketViolationWarning => 0x9c,
            BedrockPacketType::IDMotionPredictionHints => 0x9d,
            BedrockPacketType::IDAnimateEntity => 0x9e,
            BedrockPacketType::IDCameraShake => 0x9f,
            BedrockPacketType::IDPlayerFog => 0xa0,
            BedrockPacketType::IDCorrectPlayerMovePrediction => 0xa1,
            BedrockPacketType::IDItemRegistry => 0xa2,
            BedrockPacketType::IDClientBoundDebugRenderer => 0xa4,
            BedrockPacketType::IDSyncActorProperty => 0xa5,
            BedrockPacketType::IDAddVolumeEntity => 0xa6,
            BedrockPacketType::IDRemoveVolumeEntity => 0xa7,
            BedrockPacketType::IDSimulationType => 0xa8,
            BedrockPacketType::IDNpcDialogue => 0xa9,
            BedrockPacketType::IDEduUriResource => 0xaa,
            BedrockPacketType::IDCreatePhoto => 0xab,
            BedrockPacketType::IDUpdateSubChunkBlocks => 0xac,
            BedrockPacketType::IDSubChunk => 0xae,
            BedrockPacketType::IDSubChunkRequest => 0xaf,
            BedrockPacketType::IDPlayerStartItemCooldown => 0xb0,
            BedrockPacketType::IDScriptMessage => 0xb1,
            BedrockPacketType::IDCodeBuilderSource => 0xb2,
            BedrockPacketType::IDTickingAreasLoadStatus => 0xb3,
            BedrockPacketType::IDDimensionData => 0xb4,
            BedrockPacketType::IDAgentActionEvent => 0xb5,
            BedrockPacketType::IDChangeMobProperty => 0xb6,
            BedrockPacketType::IDLessonProgress => 0xb7,
            BedrockPacketType::IDRequestAbility => 0xb8,
            BedrockPacketType::IDRequestPermissions => 0xb9,
            BedrockPacketType::IDToastRequest => 0xba,
            BedrockPacketType::IDUpdateAbilities => 0xbb,
            BedrockPacketType::IDUpdateAdventureSettings => 0xbc,
            BedrockPacketType::IDDeathInfo => 0xbd,
            BedrockPacketType::IDEditorNetwork => 0xbe,
            BedrockPacketType::IDFeatureRegistry => 0xbf,
            BedrockPacketType::IDServerStats => 0xc0,
            BedrockPacketType::IDRequestNetworkSettings => 0xc1,
            BedrockPacketType::IDGameTestRequest => 0xc2,
            BedrockPacketType::IDGameTestResults => 0xc3,
            BedrockPacketType::IDUpdateClientInputLocks => 0xc4,
            BedrockPacketType::IDCameraPresets => 0xc6,
            BedrockPacketType::IDUnlockedRecipes => 0xc7,
            BedrockPacketType::IDCameraInstruction => 0x12c,
            BedrockPacketType::IDTrimData => 0x12e,
            BedrockPacketType::IDOpenSign => 0x12f,
            BedrockPacketType::IDAgentAnimation => 0x130,
            BedrockPacketType::IDRefreshEntitlements => 0x131,
            BedrockPacketType::IDPlayerToggleCrafterSlotRequest => 0x132,
            BedrockPacketType::IDSetPlayerInventoryOptions => 0x133,
            BedrockPacketType::IDSetHud => 0x134,
            BedrockPacketType::IDAwardAchievement => 0x135,
            BedrockPacketType::IDClientBoundCloseForm => 0x136,
            BedrockPacketType::IDServerBoundLoadingScreen => 0x138,
            BedrockPacketType::IDJigsawStructureData => 0x139,
            BedrockPacketType::IDCurrentStructureFeature => 0x13a,
            BedrockPacketType::IDServerBoundDiagnostics => 0x13b,
            BedrockPacketType::IDCameraAimAssist => 0x13c,
            BedrockPacketType::IDContainerRegistryCleanup => 0x13d,
            BedrockPacketType::IDMovementEffect => 0x13e,
            BedrockPacketType::IDCameraAimAssistPresets => 0x140,
            BedrockPacketType::IDClientCameraAimAssist => 0x141,
            BedrockPacketType::IDClientMovementPredictionSync => 0x142,
            BedrockPacketType::IDUpdateClientOptions => 0x143,
            BedrockPacketType::IDPlayerVideoCapture => 0x144,
            BedrockPacketType::IDPlayerUpdateEntityOverrides => 0x145,
            BedrockPacketType::IDPlayerLocation => 0x146,
            BedrockPacketType::IDClientBoundControlSchemeSet => 0x147,
            BedrockPacketType::IDPrimitiveShapes => 0x148,
            BedrockPacketType::IDServerBoundPackSettingChange => 0x149,
            BedrockPacketType::IDClientBoundDataStore => 0x14a,
            BedrockPacketType::IDGraphicsOverrideParameter => 0x14b,
            BedrockPacketType::IDServerBoundDataStore => 0x14c,
            BedrockPacketType::IDClientBoundDataDrivenUIShowScreen => 0x14d,
            BedrockPacketType::IDClientBoundDataDrivenUICloseScreen => 0x14e,
            BedrockPacketType::IDClientBoundDataDrivenUIReload => 0x14f,
            BedrockPacketType::IDClientBoundTextureShift => 0x150,
            BedrockPacketType::IDVoxelShapes => 0x151,
            BedrockPacketType::IDCameraSpline => 0x152,
            BedrockPacketType::IDCameraAimAssistActorPriority => 0x153,
            BedrockPacketType::IDResourcePacksReadyForValidation => 0x154,
            BedrockPacketType::IDLocatorBar => 0x155,
            BedrockPacketType::IDPartyChanged => 0x156,
            BedrockPacketType::IDServerBoundDataDrivenScreenClosed => 0x157,
            BedrockPacketType::IDSyncWorldClocks => 0x158,
            BedrockPacketType::IDClientBoundAttributeLayerSync => 0x159,
            BedrockPacketType::IDServerStoreInfo => 0x15a,
            BedrockPacketType::IDServerPresenceInfo => 0x15b,
            _ => 0,
        }
    }
    pub fn get_packet_name(id: u16) -> &'static str {
        match id {
            0x01 => "Login",
            0x02 => "Play Status",
            0x03 => "Server To Client Handshake",
            0x04 => "Client To Server Handshake",
            0x05 => "Disconnect",
            0x06 => "Resource Packs Info",
            0x07 => "Resource Pack Stack",
            0x08 => "Resource Pack Client Response",
            0x09 => "Text",
            0x0a => "Set Time",
            0x0b => "Start Game",
            0x0c => "Add Player",
            0x0d => "Add Actor",
            0x0e => "Remove Actor",
            0x0f => "Add Item Actor",
            0x10 => "Server Player Post Move Position",
            0x11 => "Take Item Actor",
            0x12 => "Move Actor Absolute",
            0x13 => "Move Player",
            0x15 => "Update Block",
            0x16 => "Add Painting",
            0x19 => "Level Event",
            0x1a => "Block Event",
            0x1b => "Actor Event",
            0x1c => "Mob Effect",
            0x1d => "Update Attributes",
            0x1e => "Inventory Transaction",
            0x1f => "Mob Equipment",
            0x20 => "Mob Armor Equipment",
            0x21 => "Interact",
            0x22 => "Block Pick Request",
            0x23 => "Actor Pick Request",
            0x24 => "Player Action",
            0x26 => "Hurt Armor",
            0x27 => "Set Actor Data",
            0x28 => "Set Actor Motion",
            0x29 => "Set Actor Link",
            0x2a => "Set Health",
            0x2b => "Set Spawn Position",
            0x2c => "Animate",
            0x2d => "Respawn",
            0x2e => "Container Open",
            0x2f => "Container Close",
            0x30 => "Player Hotbar",
            0x31 => "Inventory Content",
            0x32 => "Inventory Slot",
            0x33 => "Container Set Data",
            0x34 => "Crafting Data",
            0x36 => "GUI Data Pick Item",
            0x38 => "Block Actor Data",
            0x3a => "Level Chunk",
            0x3b => "Set Commands Enabled",
            0x3c => "Set Difficulty",
            0x3d => "Change Dimension",
            0x3e => "Set Player Game Type",
            0x3f => "Player List",
            0x40 => "Simple Event",
            0x41 => "Legacy Telemetry Event",
            0x42 => "Spawn Experience Orb",
            0x43 => "Client Bound Map Item Data",
            0x44 => "Map Info Request",
            0x45 => "Request Chunk Radius",
            0x46 => "Chunk Radius Updated",
            0x48 => "Game Rules Changed",
            0x49 => "Camera",
            0x4a => "Boss Event",
            0x4b => "Show Credits",
            0x4c => "Available Commands",
            0x4d => "Command Request",
            0x4e => "Command Block Update",
            0x4f => "Command Output",
            0x50 => "Update Trade",
            0x51 => "Update Equip",
            0x52 => "Resource Pack Data Info",
            0x53 => "Resource Pack Chunk Data",
            0x54 => "Resource Pack Chunk Request",
            0x55 => "Transfer",
            0x56 => "Play Sound",
            0x57 => "Stop Sound",
            0x58 => "Set Title",
            0x59 => "Add Behavior Tree",
            0x5a => "Structure Block Update",
            0x5b => "Show Store Offer",
            0x5c => "Purchase Receipt",
            0x5d => "Player Skin",
            0x5e => "Sub Client Login",
            0x5f => "Automation Client Connect",
            0x60 => "Set Last Hurt By",
            0x61 => "Book Edit",
            0x62 => "NPC Request",
            0x63 => "Photo Transfer",
            0x64 => "Modal Form Request",
            0x65 => "Modal Form Response",
            0x66 => "Server Settings Request",
            0x67 => "Server Settings Response",
            0x68 => "Show Profile",
            0x69 => "Set Default Game Type",
            0x6a => "Remove Objective",
            0x6b => "Set Display Objective",
            0x6c => "Set Score",
            0x6d => "Lab Table",
            0x6e => "Update Block Synced",
            0x6f => "Move Actor Delta",
            0x70 => "Set Scoreboard Identity",
            0x71 => "Set Local Player As Initialized",
            0x72 => "Update Soft Enum",
            0x73 => "Network Stack Latency",
            0x76 => "Spawn Particle Event",
            0x77 => "Available Actor Identifiers",
            0x79 => "Network Chunk Publisher Update",
            0x7a => "Biome Definition List",
            0x7b => "Level Sound Event",
            0x7c => "Level Event Generic",
            0x7d => "Lectern Update",
            0x81 => "Client Cache Status",
            0x82 => "On Screen Texture Animation",
            0x83 => "Map Create Locked Copy",
            0x84 => "Structure Template Data Request",
            0x85 => "Structure Template Data Response",
            0x87 => "Client Cache Blob Status",
            0x88 => "Client Cache Miss Response",
            0x89 => "Education Settings",
            0x8a => "Emote",
            0x8b => "Multiplayer Settings",
            0x8c => "Settings Command",
            0x8d => "Anvil Damage",
            0x8e => "Completed Using Item",
            0x8f => "Network Settings",
            0x90 => "Player Auth Input",
            0x91 => "Creative Content",
            0x92 => "Player Enchant Options",
            0x93 => "Item Stack Request",
            0x94 => "Item Stack Response",
            0x95 => "Player Armor Damage",
            0x96 => "Code Builder",
            0x97 => "Update Player Game Type",
            0x98 => "Emote List",
            0x99 => "Position Tracking DB Server Broadcast",
            0x9a => "Position Tracking DB Client Request",
            0x9b => "Debug Info",
            0x9c => "Packet Violation Warning",
            0x9d => "Motion Prediction Hints",
            0x9e => "Animate Entity",
            0x9f => "Camera Shake",
            0xa0 => "Player Fog",
            0xa1 => "Correct Player Move Prediction",
            0xa2 => "Item Registry",
            0xa4 => "Client Bound Debug Renderer",
            0xa5 => "Sync Actor Property",
            0xa6 => "Add Volume Entity",
            0xa7 => "Remove Volume Entity",
            0xa8 => "Simulation Type",
            0xa9 => "Npc Dialogue",
            0xaa => "Edu Uri Resource",
            0xab => "Create Photo",
            0xac => "Update Sub Chunk Blocks",
            0xae => "Sub Chunk",
            0xaf => "Sub Chunk Request",
            0xb0 => "Player Start Item Cooldown",
            0xb1 => "Script Message",
            0xb2 => "Code Builder Source",
            0xb3 => "Ticking Areas Load Status",
            0xb4 => "Dimension Data",
            0xb5 => "Agent Action Event",
            0xb6 => "Change Mob Property",
            0xb7 => "Lesson Progress",
            0xb8 => "Request Ability",
            0xb9 => "Request Permissions",
            0xba => "Toast Request",
            0xbb => "Update Abilities",
            0xbc => "Update Adventure Settings",
            0xbd => "Death Info",
            0xbe => "Editor Network",
            0xbf => "Feature Registry",
            0xc0 => "Server Stats",
            0xc1 => "Request Network Settings",
            0xc2 => "Game Test Request",
            0xc3 => "Game Test Results",
            0xc4 => "Update Client Input Locks",
            0xc6 => "Camera Presets",
            0xc7 => "Unlocked Recipes",
            0x12c => "Camera Instruction",
            0x12e => "Trim Data",
            0x12f => "Open Sign",
            0x130 => "Agent Animation",
            0x131 => "Refresh Entitlements",
            0x132 => "Player Toggle Crafter Slot Request",
            0x133 => "Set Player Inventory Options",
            0x134 => "Set Hud",
            0x135 => "Award Achievement",
            0x136 => "Client Bound Close Form",
            0x138 => "Server Bound Loading Screen",
            0x139 => "Jigsaw Structure Data",
            0x13a => "Current Structure Feature",
            0x13b => "Server Bound Diagnostics",
            0x13c => "Camera Aim Assist",
            0x13d => "Container Registry Cleanup",
            0x13e => "Movement Effect",
            0x140 => "Camera Aim Assist Presets",
            0x141 => "Client Camera Aim Assist",
            0x142 => "Client Movement Prediction Sync",
            0x143 => "Update Client Options",
            0x144 => "Player Video Capture",
            0x145 => "Player Update Entity Overrides",
            0x146 => "Player Location",
            0x147 => "Client Bound Control Scheme Set",
            0x148 => "Primitive Shapes",
            0x149 => "Server Bound Pack Setting Change",
            0x14a => "Client Bound Data Store",
            0x14b => "Graphics Override Parameter",
            0x14c => "Server Bound Data Store",
            0x14d => "Client Bound Data Driven UI Show Screen",
            0x14e => "Client Bound Data Driven UI Close Screen",
            0x14f => "Client Bound Data Driven UI Reload",
            0x150 => "Client Bound Texture Shift",
            0x151 => "Voxel Shapes",
            0x152 => "Camera Spline",
            0x153 => "Camera Aim Assist Actor Priority",
            0x154 => "Resource Packs Ready For Validation",
            0x155 => "Locator Bar",
            0x156 => "Party Changed",
            0x157 => "Server Bound Data Driven Screen Closed",
            0x158 => "Sync World Clocks",
            0x159 => "Client Bound Attribute Layer Sync",
            0x15a => "Server Store Info",
            0x15b => "Server Presence Info",
            _ => "Unknown Packet",
        }
    }

    pub fn get_packet_from_id(id: u16, stream: &mut Stream) -> BedrockPacket {
        match id {
            0x01 => BedrockPacket::Login(Login::decode(stream)),
            0x02 => BedrockPacket::PlayStatus(PlayStatus::decode(stream)),
            0x03 => BedrockPacket::ServerToClientHandshake(ServerToClientHandshake::decode(stream)),
            0x04 => BedrockPacket::ClientToServerHandshake(ClientToServerHandshake::decode(stream)),
            0x05 => BedrockPacket::Disconnect(Disconnect::decode(stream)),
            0x06 => BedrockPacket::ResourcePacksInfo(ResourcePacksInfo::decode(stream)),
            0x07 => BedrockPacket::ResourcePackStack(ResourcePackStack::decode(stream)),
            0x08 => BedrockPacket::ResourcePackClientResponse(ResourcePackClientResponse::decode(stream)),
            0x09 => BedrockPacket::Text(Text::decode(stream)),
            0x0a => BedrockPacket::SetTime(SetTime::decode(stream)),
            0x0b => BedrockPacket::StartGame(StartGame::decode(stream)),
            0x0c => BedrockPacket::AddPlayer(AddPlayer::decode(stream)),
            0x0d => BedrockPacket::AddActor(AddActor::decode(stream)),
            0x0e => BedrockPacket::RemoveActor(RemoveActor::decode(stream)),
            0x0f => BedrockPacket::AddItemActor(AddItemActor::decode(stream)),
            0x10 => BedrockPacket::ServerPlayerPostMovePosition(ServerPlayerPostMovePosition::decode(stream)),
            0x11 => BedrockPacket::TakeItemActor(TakeItemActor::decode(stream)),
            0x12 => BedrockPacket::MoveActorAbsolute(MoveActorAbsolute::decode(stream)),
            0x13 => BedrockPacket::MovePlayer(MovePlayer::decode(stream)),
            0x15 => BedrockPacket::UpdateBlock(UpdateBlock::decode(stream)),
            0x16 => BedrockPacket::AddPainting(AddPainting::decode(stream)),
            0x19 => BedrockPacket::LevelEvent(LevelEvent::decode(stream)),
            0x1a => BedrockPacket::BlockEvent(BlockEvent::decode(stream)),
            0x1b => BedrockPacket::ActorEvent(ActorEvent::decode(stream)),
            0x1c => BedrockPacket::MobEffect(MobEffect::decode(stream)),
            0x1d => BedrockPacket::UpdateAttributes(UpdateAttributes::decode(stream)),
            0x1e => BedrockPacket::InventoryTransaction(InventoryTransaction::decode(stream)),
            0x1f => BedrockPacket::MobEquipment(MobEquipment::decode(stream)),
            0x20 => BedrockPacket::MobArmorEquipment(MobArmorEquipment::decode(stream)),
            0x21 => BedrockPacket::Interact(Interact::decode(stream)),
            0x22 => BedrockPacket::BlockPickRequest(BlockPickRequest::decode(stream)),
            0x23 => BedrockPacket::ActorPickRequest(ActorPickRequest::decode(stream)),
            0x24 => BedrockPacket::PlayerAction(PlayerAction::decode(stream)),
            0x26 => BedrockPacket::HurtArmor(HurtArmor::decode(stream)),
            0x27 => BedrockPacket::SetActorData(SetActorData::decode(stream)),
            0x28 => BedrockPacket::SetActorMotion(SetActorMotion::decode(stream)),
            0x29 => BedrockPacket::SetActorLink(SetActorLink::decode(stream)),
            0x2a => BedrockPacket::SetHealth(SetHealth::decode(stream)),
            0x2b => BedrockPacket::SetSpawnPosition(SetSpawnPosition::decode(stream)),
            0x2c => BedrockPacket::Animate(Animate::decode(stream)),
            0x2d => BedrockPacket::Respawn(Respawn::decode(stream)),
            0x2e => BedrockPacket::ContainerOpen(ContainerOpen::decode(stream)),
            0x2f => BedrockPacket::ContainerClose(ContainerClose::decode(stream)),
            0x30 => BedrockPacket::PlayerHotbar(PlayerHotbar::decode(stream)),
            0x31 => BedrockPacket::InventoryContent(InventoryContent::decode(stream)),
            0x32 => BedrockPacket::InventorySlot(InventorySlot::decode(stream)),
            0x33 => BedrockPacket::ContainerSetData(ContainerSetData::decode(stream)),
            0x34 => BedrockPacket::CraftingData(CraftingData::decode(stream)),
            0x36 => BedrockPacket::GUIDataPickItem(GUIDataPickItem::decode(stream)),
            0x38 => BedrockPacket::BlockActorData(BlockActorData::decode(stream)),
            0x3a => BedrockPacket::LevelChunk(LevelChunk::decode(stream)),
            0x3b => BedrockPacket::SetCommandsEnabled(SetCommandsEnabled::decode(stream)),
            0x3c => BedrockPacket::SetDifficulty(SetDifficulty::decode(stream)),
            0x3d => BedrockPacket::ChangeDimension(ChangeDimension::decode(stream)),
            0x3e => BedrockPacket::SetPlayerGameType(SetPlayerGameType::decode(stream)),
            0x3f => BedrockPacket::PlayerList(PlayerList::decode(stream)),
            0x40 => BedrockPacket::SimpleEvent(SimpleEvent::decode(stream)),
            0x41 => BedrockPacket::LegacyTelemetryEvent(LegacyTelemetryEvent::decode(stream)),
            0x42 => BedrockPacket::SpawnExperienceOrb(SpawnExperienceOrb::decode(stream)),
            0x43 => BedrockPacket::ClientBoundMapItemData(ClientBoundMapItemData::decode(stream)),
            0x44 => BedrockPacket::MapInfoRequest(MapInfoRequest::decode(stream)),
            0x45 => BedrockPacket::RequestChunkRadius(RequestChunkRadius::decode(stream)),
            0x46 => BedrockPacket::ChunkRadiusUpdated(ChunkRadiusUpdated::decode(stream)),
            0x48 => BedrockPacket::GameRulesChanged(GameRulesChanged::decode(stream)),
            0x49 => BedrockPacket::Camera(Camera::decode(stream)),
            0x4a => BedrockPacket::BossEvent(BossEvent::decode(stream)),
            0x4b => BedrockPacket::ShowCredits(ShowCredits::decode(stream)),
            0x4c => BedrockPacket::AvailableCommands(AvailableCommands::decode(stream)),
            0x4d => BedrockPacket::CommandRequest(CommandRequest::decode(stream)),
            0x4e => BedrockPacket::CommandBlockUpdate(CommandBlockUpdate::decode(stream)),
            0x4f => BedrockPacket::CommandOutput(CommandOutput::decode(stream)),
            0x50 => BedrockPacket::UpdateTrade(UpdateTrade::decode(stream)),
            0x51 => BedrockPacket::UpdateEquip(UpdateEquip::decode(stream)),
            0x52 => BedrockPacket::ResourcePackDataInfo(ResourcePackDataInfo::decode(stream)),
            0x53 => BedrockPacket::ResourcePackChunkData(ResourcePackChunkData::decode(stream)),
            0x54 => BedrockPacket::ResourcePackChunkRequest(ResourcePackChunkRequest::decode(stream)),
            0x55 => BedrockPacket::Transfer(Transfer::decode(stream)),
            0x56 => BedrockPacket::PlaySound(PlaySound::decode(stream)),
            0x57 => BedrockPacket::StopSound(StopSound::decode(stream)),
            0x58 => BedrockPacket::SetTitle(SetTitle::decode(stream)),
            0x59 => BedrockPacket::AddBehaviorTree(AddBehaviorTree::decode(stream)),
            0x5a => BedrockPacket::StructureBlockUpdate(StructureBlockUpdate::decode(stream)),
            0x5b => BedrockPacket::ShowStoreOffer(ShowStoreOffer::decode(stream)),
            0x5c => BedrockPacket::PurchaseReceipt(PurchaseReceipt::decode(stream)),
            0x5d => BedrockPacket::PlayerSkin(PlayerSkin::decode(stream)),
            0x5e => BedrockPacket::SubClientLogin(SubClientLogin::decode(stream)),
            0x5f => BedrockPacket::AutomationClientConnect(AutomationClientConnect::decode(stream)),
            0x60 => BedrockPacket::SetLastHurtBy(SetLastHurtBy::decode(stream)),
            0x61 => BedrockPacket::BookEdit(BookEdit::decode(stream)),
            0x62 => BedrockPacket::NPCRequest(NPCRequest::decode(stream)),
            0x63 => BedrockPacket::PhotoTransfer(PhotoTransfer::decode(stream)),
            0x64 => BedrockPacket::ModalFormRequest(ModalFormRequest::decode(stream)),
            0x65 => BedrockPacket::ModalFormResponse(ModalFormResponse::decode(stream)),
            0x66 => BedrockPacket::ServerSettingsRequest(ServerSettingsRequest::decode(stream)),
            0x67 => BedrockPacket::ServerSettingsResponse(ServerSettingsResponse::decode(stream)),
            0x68 => BedrockPacket::ShowProfile(ShowProfile::decode(stream)),
            0x69 => BedrockPacket::SetDefaultGameType(SetDefaultGameType::decode(stream)),
            0x6a => BedrockPacket::RemoveObjective(RemoveObjective::decode(stream)),
            0x6b => BedrockPacket::SetDisplayObjective(SetDisplayObjective::decode(stream)),
            0x6c => BedrockPacket::SetScore(SetScore::decode(stream)),
            0x6d => BedrockPacket::LabTable(LabTable::decode(stream)),
            0x6e => BedrockPacket::UpdateBlockSynced(UpdateBlockSynced::decode(stream)),
            0x6f => BedrockPacket::MoveActorDelta(MoveActorDelta::decode(stream)),
            0x70 => BedrockPacket::SetScoreboardIdentity(SetScoreboardIdentity::decode(stream)),
            0x71 => BedrockPacket::SetLocalPlayerAsInitializedPacket(SetLocalPlayerAsInitializedPacket::decode(stream)),
            0x72 => BedrockPacket::UpdateSoftEnum(UpdateSoftEnum::decode(stream)),
            0x73 => BedrockPacket::NetworkStackLatency(NetworkStackLatency::decode(stream)),
            0x76 => BedrockPacket::SpawnParticleEffect(SpawnParticleEffect::decode(stream)),
            0x77 => BedrockPacket::AvailableActorIdentifiers(AvailableActorIdentifiers::decode(stream)),
            0x79 => BedrockPacket::NetworkChunkPublisherUpdate(NetworkChunkPublisherUpdate::decode(stream)),
            0x7a => BedrockPacket::BiomeDefinitionList(BiomeDefinitionList::decode(stream)),
            0x7b => BedrockPacket::LevelSoundEvent(LevelSoundEvent::decode(stream)),
            0x7c => BedrockPacket::LevelEventGeneric(LevelEventGeneric::decode(stream)),
            0x7d => BedrockPacket::LecternUpdate(LecternUpdate::decode(stream)),
            0x81 => BedrockPacket::ClientCacheStatus(ClientCacheStatus::decode(stream)),
            0x82 => BedrockPacket::OnScreenTextureAnimation(OnScreenTextureAnimation::decode(stream)),
            0x83 => BedrockPacket::MapCreateLockedCopy(MapCreateLockedCopy::decode(stream)),
            0x84 => BedrockPacket::StructureTemplateDataRequest(StructureTemplateDataRequest::decode(stream)),
            0x85 => BedrockPacket::StructureTemplateDataResponse(StructureTemplateDataResponse::decode(stream)),
            0x87 => BedrockPacket::ClientCacheBlobStatus(ClientCacheBlobStatus::decode(stream)),
            0x88 => BedrockPacket::ClientCacheMissResponse(ClientCacheMissResponse::decode(stream)),
            0x89 => BedrockPacket::EducationSettings(EducationSettings::decode(stream)),
            0x8a => BedrockPacket::Emote(Emote::decode(stream)),
            0x8b => BedrockPacket::MultiplayerSettings(MultiplayerSettings::decode(stream)),
            0x8c => BedrockPacket::SettingsCommand(SettingsCommand::decode(stream)),
            0x8d => BedrockPacket::AnvilDamage(AnvilDamage::decode(stream)),
            0x8e => BedrockPacket::CompletedUsingItem(CompletedUsingItem::decode(stream)),
            0x8f => BedrockPacket::NetworkSettings(NetworkSettings::decode(stream)),
            0x90 => BedrockPacket::PlayerAuthInput(PlayerAuthInput::decode(stream)),
            0x91 => BedrockPacket::CreativeContent(CreativeContent::decode(stream)),
            0x92 => BedrockPacket::PlayerEnchantOptions(PlayerEnchantOptions::decode(stream)),
            0x93 => BedrockPacket::ItemStackRequest(ItemStackRequest::decode(stream)),
            0x94 => BedrockPacket::ItemStackResponse(ItemStackResponse::decode(stream)),
            0x95 => BedrockPacket::PlayerArmorDamage(PlayerArmorDamage::decode(stream)),
            0x96 => BedrockPacket::CodeBuilder(CodeBuilder::decode(stream)),
            0x97 => BedrockPacket::UpdatePlayerGameType(UpdatePlayerGameType::decode(stream)),
            0x98 => BedrockPacket::EmoteList(EmoteList::decode(stream)),
            0x99 => BedrockPacket::PositionTrackingDBServerBroadcast(PositionTrackingDBServerBroadcast::decode(stream)),
            0x9a => BedrockPacket::PositionTrackingDBClientRequest(PositionTrackingDBClientRequest::decode(stream)),
            0x9b => BedrockPacket::DebugInfo(DebugInfo::decode(stream)),
            0x9c => BedrockPacket::PacketViolationWarning(PacketViolationWarning::decode(stream)),
            0x9d => BedrockPacket::MotionPredictionHints(MotionPredictionHints::decode(stream)),
            0x9e => BedrockPacket::AnimateEntity(AnimateEntity::decode(stream)),
            0x9f => BedrockPacket::CameraShake(CameraShake::decode(stream)),
            0xa0 => BedrockPacket::PlayerFog(PlayerFog::decode(stream)),
            0xa1 => BedrockPacket::CorrectPlayerMovePrediction(CorrectPlayerMovePrediction::decode(stream)),
            0xa2 => BedrockPacket::ItemRegistry(ItemRegistry::decode(stream)),
            0xa4 => BedrockPacket::ClientBoundDebugRenderer(ClientBoundDebugRenderer::decode(stream)),
            0xa5 => BedrockPacket::SyncActorProperty(SyncActorProperty::decode(stream)),
            0xa6 => BedrockPacket::AddVolumeEntity(AddVolumeEntity::decode(stream)),
            0xa7 => BedrockPacket::RemoveVolumeEntity(RemoveVolumeEntity::decode(stream)),
            0xa8 => BedrockPacket::SimulationType(SimulationType::decode(stream)),
            0xa9 => BedrockPacket::NPCDialogue(NPCDialogue::decode(stream)),
            0xaa => BedrockPacket::EduUriResource(EduUriResource::decode(stream)),
            0xab => BedrockPacket::CreatePhoto(CreatePhoto::decode(stream)),
            0xac => BedrockPacket::UpdateSubChunkBlocks(UpdateSubChunkBlocks::decode(stream)),
            0xae => BedrockPacket::SubChunk(SubChunk::decode(stream)),
            0xaf => BedrockPacket::SubChunkRequest(SubChunkRequest::decode(stream)),
            0xb0 => BedrockPacket::PlayerStartItemCooldown(PlayerStartItemCooldown::decode(stream)),
            0xb1 => BedrockPacket::ScriptMessage(ScriptMessage::decode(stream)),
            0xb2 => BedrockPacket::CodeBuilderSource(CodeBuilderSource::decode(stream)),
            0xb3 => BedrockPacket::TickingAreasLoadStatus(TickingAreasLoadStatus::decode(stream)),
            0xb4 => BedrockPacket::DimensionData(DimensionData::decode(stream)),
            0xb5 => BedrockPacket::AgentActionEvent(AgentActionEvent::decode(stream)),
            0xb6 => BedrockPacket::ChangeMobProperty(ChangeMobProperty::decode(stream)),
            0xb7 => BedrockPacket::LessonProgress(LessonProgress::decode(stream)),
            0xb8 => BedrockPacket::RequestAbility(RequestAbility::decode(stream)),
            0xb9 => BedrockPacket::RequestPermissions(RequestPermissions::decode(stream)),
            0xba => BedrockPacket::ToastRequest(ToastRequest::decode(stream)),
            0xbb => BedrockPacket::UpdateAbilities(UpdateAbilities::decode(stream)),
            0xbc => BedrockPacket::UpdateAdventureSettings(UpdateAdventureSettings::decode(stream)),
            0xbd => BedrockPacket::DeathInfo(DeathInfo::decode(stream)),
            0xbe => BedrockPacket::EditorNetwork(EditorNetwork::decode(stream)),
            0xbf => BedrockPacket::FeatureRegistry(FeatureRegistry::decode(stream)),
            0xc0 => BedrockPacket::ServerStats(ServerStats::decode(stream)),
            0xc1 => BedrockPacket::RequestNetworkSettings(RequestNetworkSettings::decode(stream)),
            0xc2 => BedrockPacket::GameTestRequest(GameTestRequest::decode(stream)),
            0xc3 => BedrockPacket::GameTestResults(GameTestResults::decode(stream)),
            0xc4 => BedrockPacket::UpdateClientInputLocks(UpdateClientInputLocks::decode(stream)),
            0xc6 => BedrockPacket::CameraPresets(CameraPresets::decode(stream)),
            0xc7 => BedrockPacket::UnlockedRecipes(UnlockedRecipes::decode(stream)),
            0x12c => BedrockPacket::CameraInstruction(CameraInstruction::decode(stream)),
            0x12e => BedrockPacket::TrimData(TrimData::decode(stream)),
            0x12f => BedrockPacket::OpenSign(OpenSign::decode(stream)),
            0x130 => BedrockPacket::AgentAnimation(AgentAnimation::decode(stream)),
            0x131 => BedrockPacket::RefreshEntitlements(RefreshEntitlements::decode(stream)),
            0x132 => BedrockPacket::PlayerToggleCrafterSlotRequest(PlayerToggleCrafterSlotRequest::decode(stream)),
            0x133 => BedrockPacket::SetPlayerInventoryOptions(SetPlayerInventoryOptions::decode(stream)),
            0x134 => BedrockPacket::SetHud(SetHud::decode(stream)),
            0x135 => BedrockPacket::AwardAchievement(AwardAchievement::decode(stream)),
            0x136 => BedrockPacket::ClientBoundCloseForm(ClientBoundCloseForm::decode(stream)),
            0x138 => BedrockPacket::ServerBoundLoadingScreen(ServerBoundLoadingScreen::decode(stream)),
            0x139 => BedrockPacket::JigsawStructureData(JigsawStructureData::decode(stream)),
            0x13a => BedrockPacket::CurrentStructureFeature(CurrentStructureFeature::decode(stream)),
            0x13b => BedrockPacket::ServerBoundDiagnostics(ServerBoundDiagnostics::decode(stream)),
            0x13c => BedrockPacket::CameraAimAssist(CameraAimAssist::decode(stream)),
            0x13d => BedrockPacket::ContainerRegistryCleanup(ContainerRegistryCleanup::decode(stream)),
            0x13e => BedrockPacket::MovementEffect(MovementEffect::decode(stream)),
            0x140 => BedrockPacket::CameraAimAssistPresets(CameraAimAssistPresets::decode(stream)),
            0x141 => BedrockPacket::ClientCameraAimAssist(ClientCameraAimAssist::decode(stream)),
            0x142 => BedrockPacket::ClientMovementPredictionSync(ClientMovementPredictionSync::decode(stream)),
            0x143 => BedrockPacket::UpdateClientOptions(UpdateClientOptions::decode(stream)),
            0x144 => BedrockPacket::PlayerVideoCapture(PlayerVideoCapture::decode(stream)),
            0x145 => BedrockPacket::PlayerUpdateEntityOverrides(PlayerUpdateEntityOverrides::decode(stream)),
            0x146 => BedrockPacket::PlayerLocation(PlayerLocation::decode(stream)),
            0x147 => BedrockPacket::ClientBoundControlSchemeSet(ClientBoundControlSchemeSet::decode(stream)),
            0x148 => BedrockPacket::PrimitiveShapes(PrimitiveShapes::decode(stream)),
            0x149 => BedrockPacket::ServerBoundPackSettingChange(ServerBoundPackSettingChange::decode(stream)),
            0x14a => BedrockPacket::ClientBoundDataStore(ClientBoundDataStore::decode(stream)),
            0x14b => BedrockPacket::GraphicsOverrideParameter(GraphicsOverrideParameter::decode(stream)),
            0x14c => BedrockPacket::ServerBoundDataStore(ServerBoundDataStore::decode(stream)),
            0x14d => BedrockPacket::ClientBoundDataDrivenUIShowScreen(ClientBoundDataDrivenUIShowScreen::decode(stream)),
            0x14e => BedrockPacket::ClientBoundDataDrivenUICloseScreen(ClientBoundDataDrivenUICloseScreen::decode(stream)),
            0x14f => BedrockPacket::ClientBoundDataDrivenUIReload(ClientBoundDataDrivenUIReload::decode(stream)),
            0x150 => BedrockPacket::ClientBoundTextureShift(ClientBoundTextureShift::decode(stream)),
            0x151 => BedrockPacket::VoxelShapes(VoxelShapes::decode(stream)),
            0x152 => BedrockPacket::CameraSpline(CameraSpline::decode(stream)),
            0x153 => BedrockPacket::CameraAimAssistActorPriority(CameraAimAssistActorPriority::decode(stream)),
            0x154 => BedrockPacket::ResourcePacksReadyForValidation(ResourcePacksReadyForValidation::decode(stream)),
            0x155 => BedrockPacket::LocatorBar(LocatorBar::decode(stream)),
            0x156 => BedrockPacket::PartyChanged(PartyChanged::decode(stream)),
            0x157 => BedrockPacket::ServerBoundDataDrivenScreenClosed(ServerBoundDataDrivenScreenClosed::decode(stream)),
            0x158 => BedrockPacket::SyncWorldClocks(SyncWorldClocks::decode(stream)),
            0x159 => BedrockPacket::ClientBoundAttributeLayerSync(ClientBoundAttributeLayerSync::decode(stream)),
            0x15a => BedrockPacket::ServerStoreInfo(ServerStoreInfo::decode(stream)),
            0x15b => BedrockPacket::ServerPresenceInfo(ServerPresenceInfo::decode(stream)),
            _ => BedrockPacket::Unknown(Unknown::decode(stream)),
        }
    }
}

pub enum BedrockPacket {
    Login(Login),
    PlayStatus(PlayStatus),
    ServerToClientHandshake(ServerToClientHandshake),
    ClientToServerHandshake(ClientToServerHandshake),
    Disconnect(Disconnect),
    ResourcePacksInfo(ResourcePacksInfo),
    ResourcePackStack(ResourcePackStack),
    ResourcePackClientResponse(ResourcePackClientResponse),
    Text(Text),
    SetTime(SetTime),
    StartGame(StartGame),
    AddPlayer(AddPlayer),
    AddActor(AddActor),
    RemoveActor(RemoveActor),
    AddItemActor(AddItemActor),
    ServerPlayerPostMovePosition(ServerPlayerPostMovePosition),
    TakeItemActor(TakeItemActor),
    MoveActorAbsolute(MoveActorAbsolute),
    MovePlayer(MovePlayer),
    UpdateBlock(UpdateBlock),
    AddPainting(AddPainting),
    LevelEvent(LevelEvent),
    BlockEvent(BlockEvent),
    ActorEvent(ActorEvent),
    MobEffect(MobEffect),
    UpdateAttributes(UpdateAttributes),
    InventoryTransaction(InventoryTransaction),
    MobEquipment(MobEquipment),
    MobArmorEquipment(MobArmorEquipment),
    Interact(Interact),
    BlockPickRequest(BlockPickRequest),
    ActorPickRequest(ActorPickRequest),
    PlayerAction(PlayerAction),
    HurtArmor(HurtArmor),
    SetActorData(SetActorData),
    SetActorMotion(SetActorMotion),
    SetActorLink(SetActorLink),
    SetHealth(SetHealth),
    SetSpawnPosition(SetSpawnPosition),
    Animate(Animate),
    Respawn(Respawn),
    ContainerOpen(ContainerOpen),
    ContainerClose(ContainerClose),
    PlayerHotbar(PlayerHotbar),
    InventoryContent(InventoryContent),
    InventorySlot(InventorySlot),
    ContainerSetData(ContainerSetData),
    CraftingData(CraftingData),
    GUIDataPickItem(GUIDataPickItem),
    BlockActorData(BlockActorData),
    LevelChunk(LevelChunk),
    SetCommandsEnabled(SetCommandsEnabled),
    SetDifficulty(SetDifficulty),
    ChangeDimension(ChangeDimension),
    SetPlayerGameType(SetPlayerGameType),
    PlayerList(PlayerList),
    SimpleEvent(SimpleEvent),
    LegacyTelemetryEvent(LegacyTelemetryEvent),
    SpawnExperienceOrb(SpawnExperienceOrb),
    ClientBoundMapItemData(ClientBoundMapItemData),
    MapInfoRequest(MapInfoRequest),
    RequestChunkRadius(RequestChunkRadius),
    ChunkRadiusUpdated(ChunkRadiusUpdated),
    GameRulesChanged(GameRulesChanged),
    Camera(Camera),
    BossEvent(BossEvent),
    ShowCredits(ShowCredits),
    AvailableCommands(AvailableCommands),
    CommandRequest(CommandRequest),
    CommandBlockUpdate(CommandBlockUpdate),
    CommandOutput(CommandOutput),
    UpdateTrade(UpdateTrade),
    UpdateEquip(UpdateEquip),
    ResourcePackDataInfo(ResourcePackDataInfo),
    ResourcePackChunkData(ResourcePackChunkData),
    ResourcePackChunkRequest(ResourcePackChunkRequest),
    Transfer(Transfer),
    PlaySound(PlaySound),
    StopSound(StopSound),
    SetTitle(SetTitle),
    AddBehaviorTree(AddBehaviorTree),
    StructureBlockUpdate(StructureBlockUpdate),
    ShowStoreOffer(ShowStoreOffer),
    PurchaseReceipt(PurchaseReceipt),
    PlayerSkin(PlayerSkin),
    SubClientLogin(SubClientLogin),
    AutomationClientConnect(AutomationClientConnect),
    SetLastHurtBy(SetLastHurtBy),
    BookEdit(BookEdit),
    NPCRequest(NPCRequest),
    PhotoTransfer(PhotoTransfer),
    ModalFormRequest(ModalFormRequest),
    ModalFormResponse(ModalFormResponse),
    ServerSettingsRequest(ServerSettingsRequest),
    ServerSettingsResponse(ServerSettingsResponse),
    ShowProfile(ShowProfile),
    SetDefaultGameType(SetDefaultGameType),
    RemoveObjective(RemoveObjective),
    SetDisplayObjective(SetDisplayObjective),
    SetScore(SetScore),
    LabTable(LabTable),
    UpdateBlockSynced(UpdateBlockSynced),
    MoveActorDelta(MoveActorDelta),
    SetScoreboardIdentity(SetScoreboardIdentity),
    SetLocalPlayerAsInitializedPacket(SetLocalPlayerAsInitializedPacket),
    UpdateSoftEnum(UpdateSoftEnum),
    NetworkStackLatency(NetworkStackLatency),
    SpawnParticleEffect(SpawnParticleEffect),
    AvailableActorIdentifiers(AvailableActorIdentifiers),
    NetworkChunkPublisherUpdate(NetworkChunkPublisherUpdate),
    BiomeDefinitionList(BiomeDefinitionList),
    LevelSoundEvent(LevelSoundEvent),
    LevelEventGeneric(LevelEventGeneric),
    LecternUpdate(LecternUpdate),
    ClientCacheStatus(ClientCacheStatus),
    OnScreenTextureAnimation(OnScreenTextureAnimation),
    MapCreateLockedCopy(MapCreateLockedCopy),
    StructureTemplateDataRequest(StructureTemplateDataRequest),
    StructureTemplateDataResponse(StructureTemplateDataResponse),
    ClientCacheBlobStatus(ClientCacheBlobStatus),
    ClientCacheMissResponse(ClientCacheMissResponse),
    EducationSettings(EducationSettings),
    Emote(Emote),
    MultiplayerSettings(MultiplayerSettings),
    SettingsCommand(SettingsCommand),
    AnvilDamage(AnvilDamage),
    CompletedUsingItem(CompletedUsingItem),
    NetworkSettings(NetworkSettings),
    PlayerAuthInput(PlayerAuthInput),
    CreativeContent(CreativeContent),
    PlayerEnchantOptions(PlayerEnchantOptions),
    ItemStackRequest(ItemStackRequest),
    ItemStackResponse(ItemStackResponse),
    PlayerArmorDamage(PlayerArmorDamage),
    CodeBuilder(CodeBuilder),
    UpdatePlayerGameType(UpdatePlayerGameType),
    EmoteList(EmoteList),
    PositionTrackingDBServerBroadcast(PositionTrackingDBServerBroadcast),
    PositionTrackingDBClientRequest(PositionTrackingDBClientRequest),
    DebugInfo(DebugInfo),
    PacketViolationWarning(PacketViolationWarning),
    MotionPredictionHints(MotionPredictionHints),
    AnimateEntity(AnimateEntity),
    CameraShake(CameraShake),
    PlayerFog(PlayerFog),
    CorrectPlayerMovePrediction(CorrectPlayerMovePrediction),
    ItemRegistry(ItemRegistry),
    ClientBoundDebugRenderer(ClientBoundDebugRenderer),
    SyncActorProperty(SyncActorProperty),
    AddVolumeEntity(AddVolumeEntity),
    RemoveVolumeEntity(RemoveVolumeEntity),
    SimulationType(SimulationType),
    NPCDialogue(NPCDialogue),
    EduUriResource(EduUriResource),
    CreatePhoto(CreatePhoto),
    UpdateSubChunkBlocks(UpdateSubChunkBlocks),
    SubChunk(SubChunk),
    SubChunkRequest(SubChunkRequest),
    PlayerStartItemCooldown(PlayerStartItemCooldown),
    ScriptMessage(ScriptMessage),
    CodeBuilderSource(CodeBuilderSource),
    TickingAreasLoadStatus(TickingAreasLoadStatus),
    DimensionData(DimensionData),
    AgentActionEvent(AgentActionEvent),
    ChangeMobProperty(ChangeMobProperty),
    LessonProgress(LessonProgress),
    RequestAbility(RequestAbility),
    RequestPermissions(RequestPermissions),
    ToastRequest(ToastRequest),
    UpdateAbilities(UpdateAbilities),
    UpdateAdventureSettings(UpdateAdventureSettings),
    DeathInfo(DeathInfo),
    EditorNetwork(EditorNetwork),
    FeatureRegistry(FeatureRegistry),
    ServerStats(ServerStats),
    RequestNetworkSettings(RequestNetworkSettings),
    GameTestRequest(GameTestRequest),
    GameTestResults(GameTestResults),
    UpdateClientInputLocks(UpdateClientInputLocks),
    CameraPresets(CameraPresets),
    UnlockedRecipes(UnlockedRecipes),
    CameraInstruction(CameraInstruction),
    TrimData(TrimData),
    OpenSign(OpenSign),
    AgentAnimation(AgentAnimation),
    RefreshEntitlements(RefreshEntitlements),
    PlayerToggleCrafterSlotRequest(PlayerToggleCrafterSlotRequest),
    SetPlayerInventoryOptions(SetPlayerInventoryOptions),
    SetHud(SetHud),
    AwardAchievement(AwardAchievement),
    ClientBoundCloseForm(ClientBoundCloseForm),
    ServerBoundLoadingScreen(ServerBoundLoadingScreen),
    JigsawStructureData(JigsawStructureData),
    CurrentStructureFeature(CurrentStructureFeature),
    ServerBoundDiagnostics(ServerBoundDiagnostics),
    CameraAimAssist(CameraAimAssist),
    ContainerRegistryCleanup(ContainerRegistryCleanup),
    MovementEffect(MovementEffect),
    CameraAimAssistPresets(CameraAimAssistPresets),
    ClientCameraAimAssist(ClientCameraAimAssist),
    ClientMovementPredictionSync(ClientMovementPredictionSync),
    UpdateClientOptions(UpdateClientOptions),
    PlayerVideoCapture(PlayerVideoCapture),
    PlayerUpdateEntityOverrides(PlayerUpdateEntityOverrides),
    PlayerLocation(PlayerLocation),
    ClientBoundControlSchemeSet(ClientBoundControlSchemeSet),
    PrimitiveShapes(PrimitiveShapes),
    ServerBoundPackSettingChange(ServerBoundPackSettingChange),
    ClientBoundDataStore(ClientBoundDataStore),
    GraphicsOverrideParameter(GraphicsOverrideParameter),
    ServerBoundDataStore(ServerBoundDataStore),
    ClientBoundDataDrivenUIShowScreen(ClientBoundDataDrivenUIShowScreen),
    ClientBoundDataDrivenUICloseScreen(ClientBoundDataDrivenUICloseScreen),
    ClientBoundDataDrivenUIReload(ClientBoundDataDrivenUIReload),
    ClientBoundTextureShift(ClientBoundTextureShift),
    VoxelShapes(VoxelShapes),
    CameraSpline(CameraSpline),
    CameraAimAssistActorPriority(CameraAimAssistActorPriority),
    ResourcePacksReadyForValidation(ResourcePacksReadyForValidation),
    LocatorBar(LocatorBar),
    PartyChanged(PartyChanged),
    ServerBoundDataDrivenScreenClosed(ServerBoundDataDrivenScreenClosed),
    SyncWorldClocks(SyncWorldClocks),
    ClientBoundAttributeLayerSync(ClientBoundAttributeLayerSync),
    ServerStoreInfo(ServerStoreInfo),
    ServerPresenceInfo(ServerPresenceInfo),
    Unknown(Unknown),
}