pub struct EntityMetadataProperties {}

impl EntityMetadataProperties {
    pub const FLAGS: u32 = 0;
    pub const HEALTH: u32 = 1; //int (minecart/boat)
    pub const VARIANT: u32 = 2; //int
    pub const COLOR: u32 = 3; //byte
    pub const NAMETAG: u32 = 4; //string
    pub const OWNER_EID: u32 = 5; //long
    pub const TARGET_EID: u32 = 6; //long
    pub const AIR: u32 = 7; //short
    pub const POTION_COLOR: u32 = 8; //int (ARGB!)
    pub const POTION_AMBIENT: u32 = 9; //byte
    pub const JUMP_DURATION: u32 = 10; //byte
    pub const HURT_TIME: u32 = 11; //int (minecart/boat)
    pub const HURT_DIRECTION: u32 = 12; //int (minecart/boat)
    pub const PADDLE_TIME_LEFT: u32 = 13; //float
    pub const PADDLE_TIME_RIGHT: u32 = 14; //float
    pub const EXPERIENCE_VALUE: u32 = 15; //int (xp orb)
    pub const MINECART_DISPLAY_BLOCK: u32 = 16; //int (block runtime ID)
    pub const HORSE_FLAGS: u32 = 16; //int
    pub const FIREWORK_ITEM: u32 = 16; //compoundtag
    /* 16 (byte) used by wither skull */
    pub const MINECART_DISPLAY_OFFSET: u32 = 17; //int
    pub const SHOOTER_ID: u32 = 17; //long (used by arrows)
    pub const MINECART_HAS_DISPLAY: u32 = 18; //byte (must be 1 for minecart to show block inside)
    pub const HORSE_TYPE: u32 = 19; //byte
    pub const CREEPER_SWELL: u32 = 19; //int
    pub const CREEPER_SWELL_PREVIOUS: u32 = 20; //int
    pub const CREEPER_SWELL_DIRECTION: u32 = 21; //byte
    pub const CHARGE_AMOUNT: u32 = 22; //int8, used for ghasts and also crossbow charging
    pub const ENDERMAN_HELD_ITEM_ID: u32 = 23; //short
    pub const ENTITY_AGE: u32 = 24; //short
    /* 25 (int) used by horse, (byte) used by witch */
    pub const PLAYER_FLAGS: u32 = 26; //byte
    pub const PLAYER_INDEX: u32 = 27; //int, used for marker colors and agent nametag colors
    pub const PLAYER_BED_POSITION: u32 = 28; //blockpos
    pub const FIREBALL_POWER_X: u32 = 29; //float
    pub const FIREBALL_POWER_Y: u32 = 30;
    pub const FIREBALL_POWER_Z: u32 = 31;
    /* 32 (unknown) */
    pub const FISH_X: u32 = 33; //float
    pub const FISH_Z: u32 = 34; //float
    pub const FISH_ANGLE: u32 = 35; //float
    pub const POTION_AUX_VALUE: u32 = 36; //short
    pub const LEAD_HOLDER_EID: u32 = 37; //long
    pub const SCALE: u32 = 38; //float
    pub const HAS_NPC_COMPONENT: u32 = 39; //byte (???)
    pub const NPC_SKIN_INDEX: u32 = 40; //string
    pub const NPC_ACTIONS: u32 = 41; //string (maybe JSON blob?)
    pub const MAX_AIR: u32 = 42; //short
    pub const MARK_VARIANT: u32 = 43; //int
    pub const CONTAINER_TYPE: u32 = 44; //byte (ContainerComponent)
    pub const CONTAINER_BASE_SIZE: u32 = 45; //int (ContainerComponent)
    pub const CONTAINER_EXTRA_SLOTS_PER_STRENGTH: u32 = 46; //int (used for llamas, inventory size is baseSize + thisProp * strength)
    pub const BLOCK_TARGET: u32 = 47; //block coords (ender crystal)
    pub const WITHER_INVULNERABLE_TICKS: u32 = 48; //int
    pub const WITHER_TARGET_1: u32 = 49; //long
    pub const WITHER_TARGET_2: u32 = 50; //long
    pub const WITHER_TARGET_3: u32 = 51; //long
    pub const WITHER_AERIAL_ATTACK: u32 = 52; //short
    pub const BOUNDING_BOX_WIDTH: u32 = 53; //float
    pub const BOUNDING_BOX_HEIGHT: u32 = 54; //float
    pub const FUSE_LENGTH: u32 = 55; //int
    pub const RIDER_SEAT_POSITION: u32 = 56; //vector3f
    pub const RIDER_ROTATION_LOCKED: u32 = 57; //byte
    pub const RIDER_MAX_ROTATION: u32 = 58; //float
    pub const RIDER_MIN_ROTATION: u32 = 59; //float
    pub const RIDER_SEAT_ROTATION_OFFSET: u32 = 60; //TODO: find type
    pub const AREA_EFFECT_CLOUD_RADIUS: u32 = 61; //float
    pub const AREA_EFFECT_CLOUD_WAITING: u32 = 62; //int
    pub const AREA_EFFECT_CLOUD_PARTICLE_ID: u32 = 63; //int
    pub const SHULKER_PEEK_ID: u32 = 64; //int
    pub const SHULKER_ATTACH_FACE: u32 = 65; //byte
    pub const SHULKER_ATTACHED: u32 = 66; //byte (TODO: check this - comment said it was a short)
    pub const SHULKER_ATTACH_POS: u32 = 67; //block coords
    pub const TRADING_PLAYER_EID: u32 = 68; //long
    pub const CAREER: u32 = 69; //int
    pub const HAS_COMMAND_BLOCK: u32 = 70; //byte
    pub const COMMAND_BLOCK_COMMAND: u32 = 71; //string
    pub const COMMAND_BLOCK_LAST_OUTPUT: u32 = 72; //string
    pub const COMMAND_BLOCK_TRACK_OUTPUT: u32 = 73; //byte
    pub const CONTROLLING_RIDER_SEAT_NUMBER: u32 = 74; //byte
    pub const STRENGTH: u32 = 75; //int
    pub const MAX_STRENGTH: u32 = 76; //int
    pub const EVOKER_SPELL_CASTING_COLOR: u32 = 77; //int
    pub const LIMITED_LIFE: u32 = 78;
    pub const ARMOR_STAND_POSE_INDEX: u32 = 79; //int
    pub const ENDER_CRYSTAL_TIME_OFFSET: u32 = 80; //int
    pub const ALWAYS_SHOW_NAMETAG: u32 = 81; //byte: -1: u32 = default, 0: u32 = only when looked at, 1: u32 = always
    pub const COLOR_2: u32 = 82; //byte
    pub const NAME_AUTHOR: u32 = 83; //string
    pub const SCORE_TAG: u32 = 84; //string
    pub const BALLOON_ATTACHED_ENTITY: u32 = 85; //int64, entity unique ID of owner
    pub const PUFFERFISH_SIZE: u32 = 86; //byte
    pub const BOAT_BUBBLE_TIME: u32 = 87; //int (time in bubble column)
    pub const PLAYER_AGENT_EID: u32 = 88; //long
    pub const SITTING_AMOUNT: u32 = 89; //float
    pub const SITTING_AMOUNT_PREVIOUS: u32 = 90; //float
    pub const EAT_COUNTER: u32 = 91; //int (used by pandas)
    pub const FLAGS2: u32 = 92; //long (extended data flags)
    pub const LAYING_AMOUNT: u32 = 93; //float (used by pandas)
    pub const LAYING_AMOUNT_PREVIOUS: u32 = 94; //float (used by pandas)
    pub const AREA_EFFECT_CLOUD_DURATION: u32 = 95; //int
    pub const AREA_EFFECT_CLOUD_SPAWN_TIME: u32 = 96; //int
    pub const AREA_EFFECT_CLOUD_RADIUS_PER_TICK: u32 = 97; //float, usually negative
    pub const AREA_EFFECT_CLOUD_RADIUS_CHANGE_ON_PICKUP: u32 = 98; //float
    pub const AREA_EFFECT_CLOUD_PICKUP_COUNT: u32 = 99; //int
    pub const INTERACTIVE_TAG: u32 = 100; //string (button text)
    pub const TRADE_TIER: u32 = 101; //int
    pub const MAX_TRADE_TIER: u32 = 102; //int
    pub const TRADE_XP: u32 = 103; //int
    pub const SKIN_ID: u32 = 104; //int ???
    pub const SPAWNING_FRAMES: u32 = 105; //int - related to wither
    pub const COMMAND_BLOCK_TICK_DELAY: u32 = 106; //int
    pub const COMMAND_BLOCK_EXECUTE_ON_FIRST_TICK: u32 = 107; //byte
    pub const AMBIENT_SOUND_INTERVAL_MIN: u32 = 108; //float
    pub const AMBIENT_SOUND_INTERVAL_RANGE: u32 = 109; //float
    pub const AMBIENT_SOUND_EVENT: u32 = 110; //string
    pub const FALL_DAMAGE_MULTIPLIER: u32 = 111; //float
    pub const NAME_RAW_TEXT: u32 = 112; //string
    pub const CAN_RIDE_TARGET: u32 = 113; //byte
    pub const LOW_TIER_CURED_TRADE_DISCOUNT: u32 = 114; //int
    pub const HIGH_TIER_CURED_TRADE_DISCOUNT: u32 = 115; //int
    pub const NEARBY_CURED_TRADE_DISCOUNT: u32 = 116; //int
    pub const NEARBY_CURED_DISCOUNT_TIME_STAMP: u32 = 117; //int
    pub const HITBOX: u32 = 118; //compound
    pub const IS_BUOYANT: u32 = 119; //byte
    pub const FREEZING_EFFECT_STRENGTH: u32 = 120; //float
    pub const BUOYANCY_DATA: u32 = 121; //string
    pub const GOAT_HORN_COUNT: u32 = 122; //int
    pub const BASE_RUNTIME_ID: u32 = 123; //string
    pub const MOVEMENT_SOUND_DISTANCE_OFFSET: u32 = 124;
    pub const HEARTBEAT_INTERVAL_TICKS: u32 = 125; //int
    pub const HEARTBEAT_LEVEL_SOUND_EVENT: u32 = 126; //int
    pub const PLAYER_DEATH_POSITION: u32 = 127; //blockpos
    pub const PLAYER_DEATH_DIMENSION: u32 = 128; //int
    pub const PLAYER_HAS_DIED: u32 = 129; //byte
    pub const COLLISION_BOX: u32 = 130; //compound
    pub const VISIBLE_MOB_EFFECTS: u32 = 131; //long (first 8 visible effects packed, 6 bits for effectId + 1 bit for ambient indicator)
    pub const FILTERED_NAME: u32 = 132; //string
    pub const BED_ENTER_POSITION: u32 = 133; //blockpos
    pub const SEAT_THIRD_PERSON_CAMERA_RADIUS: u32 = 134;
    pub const SEAT_CAMERA_RELAX_DISTANCE_SMOOTHING: u32 = 135;
    pub const AIM_ASSIST_PRIORITY_PRESET_ID: u32 = 136; //int
    pub const AIM_ASSIST_PRIORITY_CATEGORY_ID: u32 = 137; //int
    pub const AIM_ASSIST_PRIORITY_ACTOR_ID: u32 = 138; //int
}